const ru = {
  'WEBSITE IN DEVELOPMENT':'САЙТ В РАЗРАБОТКЕ','VIEW PREVIEW ↗':'ПОСМОТРЕТЬ ПРЕВЬЮ ↗','03 / IN DEVELOPMENT':'03 / В РАЗРАБОТКЕ','TRAVEL PRODUCT IN BUILD':'ТУРИСТИЧЕСКИЙ ПРОДУКТ В РАЗРАБОТКЕ',
  'OPEN': 'ОТКРЫТЬ',
  'EXPERIENCE':'ОПЫТ','CLOUD INFRASTRUCTURE':'ОБЛАЧНАЯ ИНФРАСТРУКТУРА','ACTIVE / SHIPPED PROJECTS':'АКТИВНЫЕ / ВЫПУЩЕННЫЕ ПРОЕКТЫ','STORYBOOK COMPONENTS':'КОМПОНЕНТЫ STORYBOOK','UI DESIGNED FROM ZERO':'UI СПРОЕКТИРОВАН С НУЛЯ','MARKETPLACE SHIPPED':'МАРКЕТПЛЕЙС ЗАПУЩЕН','FULL WEBSITE LIVE':'ПОЛНЫЙ САЙТ В ПРОДАКШЕНЕ',
  'LOADING EXPERIENCE': 'ЗАГРУЖАЮ ОПЫТ',
  'OPEN TO COLLABORATION · 2026': 'ОТКРЫТА К СОТРУДНИЧЕСТВУ · 2026',
  'Work': 'Проекты', 'Experience': 'Опыт', 'Skills': 'Навыки', 'Education': 'Образование', 'Contact': 'Контакты',
  'SOUND: OFF': 'ЗВУК: ВЫКЛ', 'SOUND: ON': 'ЗВУК: ВКЛ',
  'WORKSPACE ERA': 'ЭПОХА WORKSPACE', 'OPEN COMMAND CENTER': 'ОТКРЫТЬ COMMAND CENTER',
  'FULL-STACK / CLOUD / CREATIVE FRONTEND': 'FULL-STACK / CLOUD / CREATIVE FRONTEND',
  'Software engineer crafting scalable systems': 'Software engineer, создающая масштабируемые системы',
  'with a sharp eye for how they feel.': 'и внимательно относящаяся к тому, как они ощущаются.',
  'SCROLL TO EXPLORE': 'ЛИСТАЙТЕ, ЧТОБЫ ИССЛЕДОВАТЬ',
  'SELECTED EXPERIENCE': 'ИЗБРАННЫЙ ОПЫТ', '09 SIGNALS': '09 СИГНАЛОВ', 'PUBLIC PRODUCT':'ПУБЛИЧНЫЙ ПРОДУКТ', 'STUDENT TECH SYSTEMS':'СТУДЕНЧЕСКИЕ TECH-СИСТЕМЫ', 'TRAVEL PRODUCT LIVE':'ТУРИСТИЧЕСКИЙ ПРОДУКТ ЗАПУЩЕН',
  'DRAG / MOVE TO EXPLORE': 'ДВИГАЙТЕ КУРСОР', 'SCROLL VELOCITY CONTROLS THE ORBIT': 'СКОРОСТЬ СКРОЛЛА УПРАВЛЯЕТ ОРБИТОЙ',
  'INTERFACE LAYER': 'СЛОЙ ИНТЕРФЕЙСА', 'SYSTEM LAYER': 'СИСТЕМНЫЙ СЛОЙ',
  '[ TOOLCHAIN / ALWAYS EVOLVING ]':'[ ИНСТРУМЕНТЫ / ПОСТОЯННО РАЗВИВАЮТСЯ ]','TECHNOLOGY IN MOTION ↗':'ТЕХНОЛОГИИ В ДВИЖЕНИИ ↗',
  '[ TRUSTED SIGNAL / 2023—NOW ]': '[ КОМПАНИИ / 2023—СЕЙЧАС ]',
  'COMPANIES & PRODUCTS I HAVE HELPED BUILD': 'КОМПАНИИ И ПРОДУКТЫ, КОТОРЫЕ Я ПОМОГАЛА СОЗДАВАТЬ',
  '[ 00 / PROFILE ]': '[ 00 / ПРОФИЛЬ ]',
  'I build at the point where': 'Я работаю там, где',
  'robust engineering': 'надёжная инженерия',
  ', product thinking and visual precision meet.': ', продуктовое мышление и визуальная точность встречаются.',
  'BASED IN MAASTRICHT, NL': 'ЖИВУ В МААСТРИХТЕ, NL', 'WORKING WORLDWIDE': 'РАБОТАЮ ПО ВСЕМУ МИРУ',
  '[ SELECTED DELIVERY ]': '[ ИЗБРАННЫЕ РАБОТЫ ]', 'PUBLIC PROOF.': 'ПУБЛИЧНЫЕ ПРИМЕРЫ.', 'PRIVATE DEPTH.': 'БОЛЬШЕ — ПОД NDA.',
  '3 PUBLIC LINKS + NDA WORK ↘': '3 ПУБЛИЧНЫХ САЙТА + NDA ↘', 'PRODUCTION WEBSITE': 'САЙТ В ПРОДАКШЕНЕ', 'TOURISM WEBSITE':'ТУРИСТИЧЕСКИЙ САЙТ',
  "MOST OF THE WORK ISN’T PUBLIC.": 'БОЛЬШАЯ ЧАСТЬ РАБОТЫ НЕПУБЛИЧНА.',
  'Much of my production experience is built for internal company platforms, private B2B products or clients protected by NDA. The links below are public examples — not the full scope of what I have designed and shipped.': 'Значительная часть моего production-опыта — внутренние платформы компаний, частные B2B-продукты и клиентские проекты под NDA. Ссылки ниже — публичные примеры, а не полный объём спроектированных и выпущенных мной решений.',
  'INTERNAL TOOLS': 'ВНУТРЕННИЕ СИСТЕМЫ', 'B2B PLATFORMS': 'B2B-ПЛАТФОРМЫ', 'NDA PRODUCTS': 'ПРОДУКТЫ ПОД NDA',
  '[ 01 / EXPERIENCE ]': '[ 01 / ОПЫТ ]', 'SELECTED': 'ИЗБРАННЫЕ', 'SYSTEMS': 'СИСТЕМЫ',
  '2024—NOW ↘': '2024—СЕЙЧАС ↘', '01 / CURRENT': '01 / СЕЙЧАС', '02 / CURRENT': '02 / СЕЙЧАС',
  '03 / PLATFORM': '03 / ПЛАТФОРМА', '04 / PRODUCT': '04 / ПРОДУКТ', '05 / FOUNDER MODE': '05 / FOUNDER MODE',
  'JUN 2026 — NOW': 'ИЮНЬ 2026 — СЕЙЧАС', 'FEB 2026 — NOW': 'ФЕВРАЛЬ 2026 — СЕЙЧАС',
  'OCT 2025 — MAY 2026': 'ОКТЯБРЬ 2025 — МАЙ 2026', 'JAN 2025 — APR 2026': 'ЯНВАРЬ 2025 — АПРЕЛЬ 2026',
  'JUN 2025 — JAN 2026': 'ИЮНЬ 2025 — ЯНВАРЬ 2026',
  '06 / CLIENT DELIVERY': '06 / КЛИЕНТСКИЙ ПРОЕКТ', '07 / STARTUP LAB': '07 / СТАРТАП-ЛАБОРАТОРИЯ',
  'JUL 2025 — JAN 2026': 'ИЮЛЬ 2025 — ЯНВАРЬ 2026', 'MAR 2024 — JUL 2025': 'МАРТ 2024 — ИЮЛЬ 2025',
  'FULL-STACK & CLOUD DEVELOPER': 'FULL-STACK & CLOUD РАЗРАБОТЧИК', 'WEB DEVELOPER · FRONTEND LEAD': 'WEB РАЗРАБОТЧИК · FRONTEND LEAD',
  'FULL-STACK DEVELOPER': 'FULL-STACK РАЗРАБОТЧИК', 'UI/UX DESIGNER & FRONTEND DEVELOPER': 'UI/UX ДИЗАЙНЕР & FRONTEND РАЗРАБОТЧИК',
  'FOUNDER & FULL-STACK DEVELOPER': 'ОСНОВАТЕЛЬ & FULL-STACK РАЗРАБОТЧИК',
  'FRONTEND WEB DEVELOPER': 'FRONTEND WEB РАЗРАБОТЧИК',
  'Shipped the complete public website for Kicksharing Central Asia, translating client requirements into a fast, responsive production experience.': 'Разработала и выпустила публичный сайт Kicksharing Central Asia, превратив требования клиента в быстрый адаптивный production-интерфейс.',
  'Design & business collaboration': 'Работа с дизайном и бизнесом',
  'Designed and developed responsive interfaces within the ITS-TECH organization, including ITS Reg and RS: Frontend.': 'Проектировала и разрабатывала адаптивные интерфейсы в организации ITS-TECH, включая ITS Reg и RS: Frontend.',
  'Figma / UI systems': 'Figma / UI-системы',
  'Engineering backend and frontend systems for AI cloud infrastructure used in real customer environments.': 'Разрабатываю backend- и frontend-системы для AI cloud-инфраструктуры, работающей в реальных клиентских средах.',
  'Scalable architectures': 'Масштабируемая архитектура', 'Distributed systems': 'Распределённые системы', 'AI cloud infrastructure': 'AI cloud-инфраструктура',
  'Owning frontend architecture, design scope and production UI across a profitable B2B startup with 10+ active or shipped projects.': 'Отвечаю за frontend-архитектуру, дизайн и production UI прибыльного B2B-стартапа с 10+ активными и выпущенными проектами.',
  'Built and documented cloud software for radio and media production; shipped roughly 60% of the React Storybook component library.': 'Разрабатывала и документировала cloud-платформу для радио и медиапроизводства; выпустила около 60% библиотеки React Storybook-компонентов.',
  'Designed 100% of the website UI from scratch and translated the product language into responsive React interfaces.': 'С нуля спроектировала 100% UI сайта и превратила продуктовую концепцию в адаптивные React-интерфейсы.',
  'Built and shipped a modern rental marketplace with clean architecture, intuitive flows and scalable infrastructure.': 'Создала и выпустила современный rental marketplace с чистой архитектурой, понятными сценариями и масштабируемой инфраструктурой.',
  'ALSO:': 'ТАКЖЕ:', 'FRONTEND WEB DEVELOPER': 'FRONTEND WEB РАЗРАБОТЧИК',
  '[ 02 / CAPABILITIES ]': '[ 02 / КОМПЕТЕНЦИИ ]', 'ONE ENGINEER.': 'ОДИН ИНЖЕНЕР.', 'ALL LAYERS.': 'ВСЕ УРОВНИ.',
  'I move between interface details and infrastructure decisions without losing sight of the product.': 'Перехожу от деталей интерфейса к инфраструктурным решениям, не теряя из виду продукт.',
  'FULL STACK': 'FULL STACK', '[ 03 / LEARNING LOG ]': '[ 03 / ОБРАЗОВАНИЕ ]',
  "Bachelor's degree · Netherlands": 'Бакалавриат · Нидерланды', 'International Summer Program · Computer Science': 'Международная летняя программа · Computer Science',
  'Computer Science': 'Компьютерные науки',
  '[ HACKATHONS & RECOGNITION ]': '[ ХАКАТОНЫ И ДОСТИЖЕНИЯ ]', 'PROOF OF PRACTICE': 'ПРАКТИКА, ПОДТВЕРЖДЁННАЯ РЕЗУЛЬТАТОМ',
  'WEB DEVELOPMENT HACKATHON': 'ХАКАТОН ПО WEB-РАЗРАБОТКЕ', 'THREE SEPARATE HACKATHONS · PRIZE WINNER': 'ТРИ ОТДЕЛЬНЫХ ХАКАТОНА · ПРИЗЁР',
  '2025 · PRIZE WINNER': '2025 · ПРИЗЁР',
  '2026 · RECOGNIZED SOLUTION': '2026 · ОТМЕЧЕННОЕ РЕШЕНИЕ',
  'TEAM EPOCH × AIC4NL · RECOGNITION PROVIDED ACCESS TO DUTCH AI CONGRESS 2026': 'TEAM EPOCH × AIC4NL · РЕШЕНИЕ БЫЛО ОТМЕЧЕНО И ДАЛО ВОЗМОЖНОСТЬ ПОСЕТИТЬ DUTCH AI CONGRESS 2026',
  '[ 04 / START A CONVERSATION ]': '[ 04 / ДАВАЙТЕ ПОГОВОРИМ ]', "LET'S BUILD": 'ДАВАЙТЕ СОЗДАДИМ', "WHAT'S NEXT.": 'ЧТО-ТО НОВОЕ.',
  'BACK TO TOP ↑': 'НАВЕРХ ↑', 'WHERE SHOULD WE GO?': 'КУДА ПЕРЕЙДЁМ?', 'READ EXPERIENCE': 'ПОСМОТРЕТЬ ОПЫТ',
  'INSPECT THE STACK': 'ИЗУЧИТЬ СТЕК', 'START A CONVERSATION': 'НАПИСАТЬ МНЕ', 'OPEN LINKEDIN': 'ОТКРЫТЬ LINKEDIN',
  'PRESS 1—4 TO NAVIGATE · ESC TO CLOSE': 'НАЖМИТЕ 1—4 ДЛЯ НАВИГАЦИИ · ESC ЧТОБЫ ЗАКРЫТЬ'
}

const nl = {
  'WEBSITE IN DEVELOPMENT':'WEBSITE IN ONTWIKKELING','VIEW PREVIEW ↗':'BEKIJK PREVIEW ↗','03 / IN DEVELOPMENT':'03 / IN ONTWIKKELING','TRAVEL PRODUCT IN BUILD':'REISPRODUCT IN ONTWIKKELING',
  '[ TOOLCHAIN / ALWAYS EVOLVING ]':'[ TOOLCHAIN / ALTIJD IN ONTWIKKELING ]','TECHNOLOGY IN MOTION ↗':'TECHNOLOGIE IN BEWEGING ↗',
  'OPEN':'OPENEN','EXPERIENCE':'ERVARING','CLOUD INFRASTRUCTURE':'CLOUDINFRASTRUCTUUR','ACTIVE / SHIPPED PROJECTS':'ACTIEVE / OPGELEVERDE PROJECTEN','STORYBOOK COMPONENTS':'STORYBOOK-COMPONENTEN','UI DESIGNED FROM ZERO':'UI VANAF NUL ONTWORPEN','MARKETPLACE SHIPPED':'MARKTPLAATS GELANCEERD','FULL WEBSITE LIVE':'VOLLEDIGE WEBSITE LIVE',
  'Work':'Werk','Experience':'Ervaring','Skills':'Vaardigheden','Education':'Opleiding','Contact':'Contact',
  'Software engineer crafting scalable systems':'Software-engineer die schaalbare systemen bouwt','with a sharp eye for how they feel.':'met scherp oog voor hoe ze aanvoelen.',
  'SELECTED EXPERIENCE':'GESELECTEERDE ERVARING','09 SIGNALS':'09 SIGNALEN','PUBLIC PRODUCT':'PUBLIEK PRODUCT','STUDENT TECH SYSTEMS':'STUDENTEN-TECHSYSTEMEN','TRAVEL PRODUCT LIVE':'REISPRODUCT LIVE','DRAG / MOVE TO EXPLORE':'SLEEP / BEWEEG OM TE VERKENNEN','SCROLL VELOCITY CONTROLS THE ORBIT':'SCROLLSNELHEID BESTUURT DE BAAN',
  '[ TRUSTED SIGNAL / 2023—NOW ]':'[ VERTROUWD NETWERK / 2023—NU ]','COMPANIES & PRODUCTS I HAVE HELPED BUILD':'BEDRIJVEN EN PRODUCTEN WAARAAN IK HEB MEEGEBOUWD',
  '[ 00 / PROFILE ]':'[ 00 / PROFIEL ]','I build at the point where':'Ik bouw waar','robust engineering':'robuuste engineering',', product thinking and visual precision meet.':', productdenken en visuele precisie samenkomen.',
  'BASED IN MAASTRICHT, NL':'GEVESTIGD IN MAASTRICHT, NL','WORKING WORLDWIDE':'WERKT WERELDWIJD',
  '[ SELECTED DELIVERY ]':'[ GESELECTEERD WERK ]','PUBLIC PROOF.':'PUBLIEK BEWIJS.','PRIVATE DEPTH.':'PRIVATE DIEPGANG.','3 PUBLIC LINKS + NDA WORK ↘':'3 PUBLIEKE LINKS + NDA-WERK ↘','PRODUCTION WEBSITE':'LIVE WEBSITE','TOURISM WEBSITE':'TOERISTISCHE WEBSITE',
  "MOST OF THE WORK ISN’T PUBLIC.":'HET MEESTE WERK IS NIET OPENBAAR.','Much of my production experience is built for internal company platforms, private B2B products or clients protected by NDA. The links below are public examples — not the full scope of what I have designed and shipped.':'Veel van mijn productie-ervaring betreft interne bedrijfsplatforms, private B2B-producten en klanten onder NDA. De links hieronder zijn publieke voorbeelden — niet de volledige omvang van wat ik heb ontworpen en opgeleverd.',
  'INTERNAL TOOLS':'INTERNE TOOLS','B2B PLATFORMS':'B2B-PLATFORMEN','NDA PRODUCTS':'NDA-PRODUCTEN',
  '[ 01 / EXPERIENCE ]':'[ 01 / ERVARING ]','SELECTED':'GESELECTEERDE','SYSTEMS':'SYSTEMEN','2024—NOW ↘':'2024—NU ↘','01 / CURRENT':'01 / HUIDIG','02 / CURRENT':'02 / HUIDIG','03 / PLATFORM':'03 / PLATFORM','04 / PRODUCT':'04 / PRODUCT','05 / FOUNDER MODE':'05 / OPRICHTER','06 / CLIENT DELIVERY':'06 / KLANTPROJECT','07 / STARTUP LAB':'07 / START-UPLAB',
  'JUN 2026 — NOW':'JUN 2026 — NU','FEB 2026 — NOW':'FEB 2026 — NU','OCT 2025 — MAY 2026':'OKT 2025 — MEI 2026','JAN 2025 — APR 2026':'JAN 2025 — APR 2026','JUN 2025 — JAN 2026':'JUN 2025 — JAN 2026','JUL 2025 — JAN 2026':'JUL 2025 — JAN 2026','MAR 2024 — JUL 2025':'MRT 2024 — JUL 2025',
  'FULL-STACK & CLOUD DEVELOPER':'FULL-STACK- & CLOUDDEVELOPER','WEB DEVELOPER · FRONTEND LEAD':'WEBDEVELOPER · FRONTEND LEAD','FULL-STACK DEVELOPER':'FULL-STACKDEVELOPER','UI/UX DESIGNER & FRONTEND DEVELOPER':'UI/UX-DESIGNER & FRONTENDDEVELOPER','FOUNDER & FULL-STACK DEVELOPER':'OPRICHTER & FULL-STACKDEVELOPER','FRONTEND WEB DEVELOPER':'FRONTEND WEBDEVELOPER',
  'Engineering backend and frontend systems for AI cloud infrastructure used in real customer environments.':'Ontwikkelt backend- en frontendsystemen voor AI-cloudinfrastructuur in echte klantomgevingen.','Scalable architectures':'Schaalbare architecturen','Distributed systems':'Gedistribueerde systemen','AI cloud infrastructure':'AI-cloudinfrastructuur',
  'Owning frontend architecture, design scope and production UI across a profitable B2B startup with 10+ active or shipped projects.':'Verantwoordelijk voor frontendarchitectuur, design en productie-UI binnen een winstgevende B2B-start-up met 10+ actieve of opgeleverde projecten.',
  'Built and documented cloud software for radio and media production; shipped roughly 60% of the React Storybook component library.':'Bouwde en documenteerde cloudsoftware voor radio- en mediaproductie; leverde circa 60% van de React Storybook-componentbibliotheek.',
  'Designed 100% of the website UI from scratch and translated the product language into responsive React interfaces.':'Ontwierp 100% van de website-UI vanaf nul en vertaalde de producttaal naar responsieve React-interfaces.',
  'Built and shipped a modern rental marketplace with clean architecture, intuitive flows and scalable infrastructure.':'Bouwde en lanceerde een moderne verhuurmarktplaats met heldere architectuur, intuïtieve flows en schaalbare infrastructuur.',
  'Shipped the complete public website for Kicksharing Central Asia, translating client requirements into a fast, responsive production experience.':'Lanceerde de volledige publieke website voor Kicksharing Central Asia en vertaalde klanteisen naar een snelle, responsieve productie-ervaring.',
  'Designed and developed responsive interfaces within the ITS-TECH organization, including ITS Reg and RS: Frontend.':'Ontwierp en ontwikkelde responsieve interfaces binnen ITS-TECH, waaronder ITS Reg en RS: Frontend.',
  'Design & business collaboration':'Samenwerking met design en business','Figma / UI systems':'Figma / UI-systemen',
  '[ 02 / CAPABILITIES ]':'[ 02 / EXPERTISE ]','ONE ENGINEER.':'ÉÉN ENGINEER.','ALL LAYERS.':'ALLE LAGEN.','I move between interface details and infrastructure decisions without losing sight of the product.':'Ik beweeg tussen interfacedetails en infrastructuurbeslissingen zonder het product uit het oog te verliezen.',
  '[ 03 / LEARNING LOG ]':'[ 03 / OPLEIDING ]',"Bachelor's degree · Netherlands":'Bachelor · Nederland','International Summer Program · Computer Science':'Internationaal zomerprogramma · Informatica','Computer Science':'Informatica',
  '[ HACKATHONS & RECOGNITION ]':'[ HACKATHONS & ERKENNING ]','PROOF OF PRACTICE':'BEWEZEN IN DE PRAKTIJK','2025 · PRIZE WINNER':'2025 · PRIJSWINNAAR','THREE SEPARATE HACKATHONS · PRIZE WINNER':'DRIE AFZONDERLIJKE HACKATHONS · PRIJSWINNAAR','WEB DEVELOPMENT HACKATHON':'WEBDEVELOPMENT-HACKATHON','2026 · RECOGNIZED SOLUTION':'2026 · ERKEND CONCEPT','TEAM EPOCH × AIC4NL · RECOGNITION PROVIDED ACCESS TO DUTCH AI CONGRESS 2026':'TEAM EPOCH × AIC4NL · ERKENNING GAF TOEGANG TOT DUTCH AI CONGRESS 2026',
  '[ 04 / START A CONVERSATION ]':'[ 04 / START EEN GESPREK ]',"LET'S BUILD":'LATEN WE BOUWEN',"WHAT'S NEXT.":'WAT HIERNA KOMT.','BACK TO TOP ↑':'TERUG NAAR BOVEN ↑'
}

const fr = {
  'WEBSITE IN DEVELOPMENT':'SITE EN DÉVELOPPEMENT','VIEW PREVIEW ↗':'VOIR L’APERÇU ↗','03 / IN DEVELOPMENT':'03 / EN DÉVELOPPEMENT','TRAVEL PRODUCT IN BUILD':'PRODUIT TOURISTIQUE EN DÉVELOPPEMENT',
  '[ TOOLCHAIN / ALWAYS EVOLVING ]':'[ OUTILS / TOUJOURS EN ÉVOLUTION ]','TECHNOLOGY IN MOTION ↗':'TECHNOLOGIE EN MOUVEMENT ↗',
  'OPEN':'OUVRIR','EXPERIENCE':'EXPÉRIENCE','CLOUD INFRASTRUCTURE':'INFRASTRUCTURE CLOUD','ACTIVE / SHIPPED PROJECTS':'PROJETS ACTIFS / LIVRÉS','STORYBOOK COMPONENTS':'COMPOSANTS STORYBOOK','UI DESIGNED FROM ZERO':'UI CONÇUE DE ZÉRO','MARKETPLACE SHIPPED':'MARKETPLACE LANCÉE','FULL WEBSITE LIVE':'SITE COMPLET EN LIGNE',
  'Work':'Projets','Experience':'Expérience','Skills':'Compétences','Education':'Formation','Contact':'Contact',
  'Software engineer crafting scalable systems':'Ingénieure logiciel créant des systèmes évolutifs','with a sharp eye for how they feel.':'avec une attention particulière à leur ressenti.',
  'SELECTED EXPERIENCE':'EXPÉRIENCE SÉLECTIONNÉE','09 SIGNALS':'09 SIGNAUX','PUBLIC PRODUCT':'PRODUIT PUBLIC','STUDENT TECH SYSTEMS':'SYSTÈMES TECH ÉTUDIANTS','TRAVEL PRODUCT LIVE':'PRODUIT TOURISTIQUE EN LIGNE','DRAG / MOVE TO EXPLORE':'GLISSEZ / BOUGEZ POUR EXPLORER','SCROLL VELOCITY CONTROLS THE ORBIT':'LA VITESSE DU SCROLL CONTRÔLE L’ORBITE',
  '[ TRUSTED SIGNAL / 2023—NOW ]':'[ RÉSEAU DE CONFIANCE / 2023—AUJ. ]','COMPANIES & PRODUCTS I HAVE HELPED BUILD':'ENTREPRISES ET PRODUITS QUE J’AI CONTRIBUÉ À CRÉER',
  '[ 00 / PROFILE ]':'[ 00 / PROFIL ]','I build at the point where':'Je travaille là où','robust engineering':'une ingénierie robuste',', product thinking and visual precision meet.':', la vision produit et la précision visuelle se rencontrent.',
  'BASED IN MAASTRICHT, NL':'BASÉE À MAASTRICHT, NL','WORKING WORLDWIDE':'TRAVAILLE DANS LE MONDE ENTIER',
  '[ SELECTED DELIVERY ]':'[ RÉALISATIONS SÉLECTIONNÉES ]','PUBLIC PROOF.':'PREUVES PUBLIQUES.','PRIVATE DEPTH.':'EXPERTISE PRIVÉE.','3 PUBLIC LINKS + NDA WORK ↘':'3 LIENS PUBLICS + TRAVAIL SOUS NDA ↘','PRODUCTION WEBSITE':'SITE EN PRODUCTION','TOURISM WEBSITE':'SITE TOURISTIQUE',
  "MOST OF THE WORK ISN’T PUBLIC.":'LA MAJEURE PARTIE DU TRAVAIL N’EST PAS PUBLIQUE.','Much of my production experience is built for internal company platforms, private B2B products or clients protected by NDA. The links below are public examples — not the full scope of what I have designed and shipped.':'Une grande partie de mon expérience concerne des plateformes internes, des produits B2B privés ou des clients protégés par NDA. Les liens ci-dessous sont des exemples publics — pas l’ensemble de ce que j’ai conçu et livré.',
  'INTERNAL TOOLS':'OUTILS INTERNES','B2B PLATFORMS':'PLATEFORMES B2B','NDA PRODUCTS':'PRODUITS SOUS NDA',
  '[ 01 / EXPERIENCE ]':'[ 01 / EXPÉRIENCE ]','SELECTED':'SYSTÈMES','SYSTEMS':'SÉLECTIONNÉS','2024—NOW ↘':'2024—AUJ. ↘','01 / CURRENT':'01 / ACTUEL','02 / CURRENT':'02 / ACTUEL','03 / PLATFORM':'03 / PLATEFORME','04 / PRODUCT':'04 / PRODUIT','05 / FOUNDER MODE':'05 / FONDATRICE','06 / CLIENT DELIVERY':'06 / PROJET CLIENT','07 / STARTUP LAB':'07 / LAB START-UP',
  'JUN 2026 — NOW':'JUIN 2026 — AUJ.','FEB 2026 — NOW':'FÉV. 2026 — AUJ.','OCT 2025 — MAY 2026':'OCT. 2025 — MAI 2026','JAN 2025 — APR 2026':'JAN. 2025 — AVR. 2026','JUN 2025 — JAN 2026':'JUIN 2025 — JAN. 2026','JUL 2025 — JAN 2026':'JUIL. 2025 — JAN. 2026','MAR 2024 — JUL 2025':'MARS 2024 — JUIL. 2025',
  'FULL-STACK & CLOUD DEVELOPER':'DÉVELOPPEUSE FULL-STACK & CLOUD','WEB DEVELOPER · FRONTEND LEAD':'DÉVELOPPEUSE WEB · LEAD FRONTEND','FULL-STACK DEVELOPER':'DÉVELOPPEUSE FULL-STACK','UI/UX DESIGNER & FRONTEND DEVELOPER':'DESIGNER UI/UX & DÉVELOPPEUSE FRONTEND','FOUNDER & FULL-STACK DEVELOPER':'FONDATRICE & DÉVELOPPEUSE FULL-STACK','FRONTEND WEB DEVELOPER':'DÉVELOPPEUSE WEB FRONTEND',
  'Engineering backend and frontend systems for AI cloud infrastructure used in real customer environments.':'Développement de systèmes backend et frontend pour une infrastructure cloud IA utilisée dans des environnements clients réels.','Scalable architectures':'Architectures évolutives','Distributed systems':'Systèmes distribués','AI cloud infrastructure':'Infrastructure cloud IA',
  'Owning frontend architecture, design scope and production UI across a profitable B2B startup with 10+ active or shipped projects.':'Responsable de l’architecture frontend, du design et des interfaces de production d’une start-up B2B rentable avec plus de 10 projets actifs ou livrés.',
  'Built and documented cloud software for radio and media production; shipped roughly 60% of the React Storybook component library.':'Développement et documentation d’un logiciel cloud pour la production radio et média ; livraison d’environ 60 % de la bibliothèque React Storybook.',
  'Designed 100% of the website UI from scratch and translated the product language into responsive React interfaces.':'Conception de 100 % de l’interface du site et transformation du langage produit en interfaces React responsives.',
  'Built and shipped a modern rental marketplace with clean architecture, intuitive flows and scalable infrastructure.':'Création et lancement d’une marketplace de location avec une architecture claire, des parcours intuitifs et une infrastructure évolutive.',
  'Shipped the complete public website for Kicksharing Central Asia, translating client requirements into a fast, responsive production experience.':'Livraison du site public complet de Kicksharing Central Asia, transformant les exigences client en une expérience rapide et responsive.',
  'Designed and developed responsive interfaces within the ITS-TECH organization, including ITS Reg and RS: Frontend.':'Conception et développement d’interfaces responsives au sein d’ITS-TECH, notamment ITS Reg et RS: Frontend.','Design & business collaboration':'Collaboration design et métier','Figma / UI systems':'Figma / systèmes UI',
  '[ 02 / CAPABILITIES ]':'[ 02 / COMPÉTENCES ]','ONE ENGINEER.':'UNE INGÉNIEURE.','ALL LAYERS.':'TOUTES LES COUCHES.','I move between interface details and infrastructure decisions without losing sight of the product.':'Je passe des détails d’interface aux décisions d’infrastructure sans perdre de vue le produit.',
  '[ 03 / LEARNING LOG ]':'[ 03 / FORMATION ]',"Bachelor's degree · Netherlands":'Licence · Pays-Bas','International Summer Program · Computer Science':'Programme international d’été · Informatique','Computer Science':'Informatique',
  '[ HACKATHONS & RECOGNITION ]':'[ HACKATHONS & DISTINCTIONS ]','PROOF OF PRACTICE':'LA PRATIQUE COMME PREUVE','2025 · PRIZE WINNER':'2025 · LAURÉATE','THREE SEPARATE HACKATHONS · PRIZE WINNER':'TROIS HACKATHONS DISTINCTS · LAURÉATE','WEB DEVELOPMENT HACKATHON':'HACKATHON DE DÉVELOPPEMENT WEB','2026 · RECOGNIZED SOLUTION':'2026 · SOLUTION RECONNUE','TEAM EPOCH × AIC4NL · RECOGNITION PROVIDED ACCESS TO DUTCH AI CONGRESS 2026':'TEAM EPOCH × AIC4NL · LA RECONNAISSANCE A DONNÉ ACCÈS AU DUTCH AI CONGRESS 2026',
  '[ 04 / START A CONVERSATION ]':'[ 04 / COMMENÇONS À ÉCHANGER ]',"LET'S BUILD":'CRÉONS',"WHAT'S NEXT.":'LA SUITE.','BACK TO TOP ↑':'RETOUR EN HAUT ↑'
}

const es = {
  'WEBSITE IN DEVELOPMENT':'SITIO EN DESARROLLO','VIEW PREVIEW ↗':'VER PREVIEW ↗','03 / IN DEVELOPMENT':'03 / EN DESARROLLO','TRAVEL PRODUCT IN BUILD':'PRODUCTO TURÍSTICO EN DESARROLLO',
  '[ TOOLCHAIN / ALWAYS EVOLVING ]':'[ HERRAMIENTAS / SIEMPRE EVOLUCIONANDO ]','TECHNOLOGY IN MOTION ↗':'TECNOLOGÍA EN MOVIMIENTO ↗',
  'OPEN':'ABRIR','EXPERIENCE':'EXPERIENCIA','CLOUD INFRASTRUCTURE':'INFRAESTRUCTURA CLOUD','ACTIVE / SHIPPED PROJECTS':'PROYECTOS ACTIVOS / ENTREGADOS','STORYBOOK COMPONENTS':'COMPONENTES STORYBOOK','UI DESIGNED FROM ZERO':'UI DISEÑADA DESDE CERO','MARKETPLACE SHIPPED':'MARKETPLACE LANZADO','FULL WEBSITE LIVE':'SITIO COMPLETO EN PRODUCCIÓN',
  'Work':'Proyectos','Experience':'Experiencia','Skills':'Habilidades','Education':'Formación','Contact':'Contacto',
  'Software engineer crafting scalable systems':'Ingeniera de software que crea sistemas escalables','with a sharp eye for how they feel.':'con especial atención a cómo se sienten.',
  'SELECTED EXPERIENCE':'EXPERIENCIA SELECCIONADA','09 SIGNALS':'09 SEÑALES','PUBLIC PRODUCT':'PRODUCTO PÚBLICO','STUDENT TECH SYSTEMS':'SISTEMAS TECH ESTUDIANTILES','TRAVEL PRODUCT LIVE':'PRODUCTO TURÍSTICO EN LÍNEA','DRAG / MOVE TO EXPLORE':'ARRASTRA / MUEVE PARA EXPLORAR','SCROLL VELOCITY CONTROLS THE ORBIT':'LA VELOCIDAD DEL SCROLL CONTROLA LA ÓRBITA',
  '[ TRUSTED SIGNAL / 2023—NOW ]':'[ RED DE CONFIANZA / 2023—HOY ]','COMPANIES & PRODUCTS I HAVE HELPED BUILD':'EMPRESAS Y PRODUCTOS QUE HE AYUDADO A CREAR',
  '[ 00 / PROFILE ]':'[ 00 / PERFIL ]','I build at the point where':'Trabajo donde','robust engineering':'la ingeniería robusta',', product thinking and visual precision meet.':', el pensamiento de producto y la precisión visual se encuentran.',
  'BASED IN MAASTRICHT, NL':'CON BASE EN MAASTRICHT, NL','WORKING WORLDWIDE':'TRABAJO EN TODO EL MUNDO',
  '[ SELECTED DELIVERY ]':'[ TRABAJO SELECCIONADO ]','PUBLIC PROOF.':'PRUEBAS PÚBLICAS.','PRIVATE DEPTH.':'PROFUNDIDAD PRIVADA.','3 PUBLIC LINKS + NDA WORK ↘':'3 ENLACES PÚBLICOS + TRABAJO BAJO NDA ↘','PRODUCTION WEBSITE':'SITIO EN PRODUCCIÓN','TOURISM WEBSITE':'SITIO TURÍSTICO',
  "MOST OF THE WORK ISN’T PUBLIC.":'LA MAYOR PARTE DEL TRABAJO NO ES PÚBLICO.','Much of my production experience is built for internal company platforms, private B2B products or clients protected by NDA. The links below are public examples — not the full scope of what I have designed and shipped.':'Gran parte de mi experiencia está en plataformas internas, productos B2B privados o clientes protegidos por NDA. Los enlaces son ejemplos públicos, no todo lo que he diseñado y lanzado.',
  'INTERNAL TOOLS':'HERRAMIENTAS INTERNAS','B2B PLATFORMS':'PLATAFORMAS B2B','NDA PRODUCTS':'PRODUCTOS BAJO NDA',
  '[ 01 / EXPERIENCE ]':'[ 01 / EXPERIENCIA ]','SELECTED':'SISTEMAS','SYSTEMS':'SELECCIONADOS','2024—NOW ↘':'2024—HOY ↘','01 / CURRENT':'01 / ACTUAL','02 / CURRENT':'02 / ACTUAL','03 / PLATFORM':'03 / PLATAFORMA','04 / PRODUCT':'04 / PRODUCTO','05 / FOUNDER MODE':'05 / FUNDADORA','06 / CLIENT DELIVERY':'06 / PROYECTO CLIENTE','07 / STARTUP LAB':'07 / LAB STARTUP',
  'JUN 2026 — NOW':'JUN. 2026 — HOY','FEB 2026 — NOW':'FEB. 2026 — HOY','OCT 2025 — MAY 2026':'OCT. 2025 — MAY. 2026','JAN 2025 — APR 2026':'ENE. 2025 — ABR. 2026','JUN 2025 — JAN 2026':'JUN. 2025 — ENE. 2026','JUL 2025 — JAN 2026':'JUL. 2025 — ENE. 2026','MAR 2024 — JUL 2025':'MAR. 2024 — JUL. 2025',
  'FULL-STACK & CLOUD DEVELOPER':'DESARROLLADORA FULL-STACK Y CLOUD','WEB DEVELOPER · FRONTEND LEAD':'DESARROLLADORA WEB · LEAD FRONTEND','FULL-STACK DEVELOPER':'DESARROLLADORA FULL-STACK','UI/UX DESIGNER & FRONTEND DEVELOPER':'DISEÑADORA UI/UX Y DESARROLLADORA FRONTEND','FOUNDER & FULL-STACK DEVELOPER':'FUNDADORA Y DESARROLLADORA FULL-STACK','FRONTEND WEB DEVELOPER':'DESARROLLADORA WEB FRONTEND',
  'Engineering backend and frontend systems for AI cloud infrastructure used in real customer environments.':'Desarrollo de sistemas backend y frontend para infraestructura cloud de IA utilizada en entornos reales de clientes.','Scalable architectures':'Arquitecturas escalables','Distributed systems':'Sistemas distribuidos','AI cloud infrastructure':'Infraestructura cloud de IA',
  'Owning frontend architecture, design scope and production UI across a profitable B2B startup with 10+ active or shipped projects.':'Responsable de la arquitectura frontend, el diseño y la UI de producción de una startup B2B rentable con más de 10 proyectos activos o entregados.',
  'Built and documented cloud software for radio and media production; shipped roughly 60% of the React Storybook component library.':'Desarrollé y documenté software cloud para producción de radio y medios; entregué cerca del 60 % de la biblioteca React Storybook.',
  'Designed 100% of the website UI from scratch and translated the product language into responsive React interfaces.':'Diseñé el 100 % de la UI del sitio desde cero y convertí el lenguaje del producto en interfaces React responsivas.',
  'Built and shipped a modern rental marketplace with clean architecture, intuitive flows and scalable infrastructure.':'Creé y lancé un marketplace de alquiler con arquitectura limpia, flujos intuitivos e infraestructura escalable.',
  'Shipped the complete public website for Kicksharing Central Asia, translating client requirements into a fast, responsive production experience.':'Lancé el sitio público completo de Kicksharing Central Asia, transformando los requisitos del cliente en una experiencia rápida y responsiva.',
  'Designed and developed responsive interfaces within the ITS-TECH organization, including ITS Reg and RS: Frontend.':'Diseñé y desarrollé interfaces responsivas en ITS-TECH, incluyendo ITS Reg y RS: Frontend.','Design & business collaboration':'Colaboración con diseño y negocio','Figma / UI systems':'Figma / sistemas UI',
  '[ 02 / CAPABILITIES ]':'[ 02 / CAPACIDADES ]','ONE ENGINEER.':'UNA INGENIERA.','ALL LAYERS.':'TODAS LAS CAPAS.','I move between interface details and infrastructure decisions without losing sight of the product.':'Paso de los detalles de interfaz a las decisiones de infraestructura sin perder de vista el producto.',
  '[ 03 / LEARNING LOG ]':'[ 03 / FORMACIÓN ]',"Bachelor's degree · Netherlands":'Grado universitario · Países Bajos','International Summer Program · Computer Science':'Programa internacional de verano · Informática','Computer Science':'Informática',
  '[ HACKATHONS & RECOGNITION ]':'[ HACKATHONES Y RECONOCIMIENTOS ]','PROOF OF PRACTICE':'PRÁCTICA DEMOSTRADA','2025 · PRIZE WINNER':'2025 · PREMIADA','THREE SEPARATE HACKATHONS · PRIZE WINNER':'TRES HACKATHONES DISTINTOS · PREMIADA','WEB DEVELOPMENT HACKATHON':'HACKATHÓN DE DESARROLLO WEB','2026 · RECOGNIZED SOLUTION':'2026 · SOLUCIÓN RECONOCIDA','TEAM EPOCH × AIC4NL · RECOGNITION PROVIDED ACCESS TO DUTCH AI CONGRESS 2026':'TEAM EPOCH × AIC4NL · EL RECONOCIMIENTO DIO ACCESO AL DUTCH AI CONGRESS 2026',
  '[ 04 / START A CONVERSATION ]':'[ 04 / EMPECEMOS A HABLAR ]',"LET'S BUILD":'CONSTRUYAMOS',"WHAT'S NEXT.":'LO QUE SIGUE.','BACK TO TOP ↑':'VOLVER ARRIBA ↑'
}

const de = {
  'WEBSITE IN DEVELOPMENT':'WEBSITE IN ENTWICKLUNG','VIEW PREVIEW ↗':'VORSCHAU ANSEHEN ↗','03 / IN DEVELOPMENT':'03 / IN ENTWICKLUNG','TRAVEL PRODUCT IN BUILD':'REISEPRODUKT IN ENTWICKLUNG',
  '[ TOOLCHAIN / ALWAYS EVOLVING ]':'[ TOOLCHAIN / STÄNDIG IN BEWEGUNG ]','TECHNOLOGY IN MOTION ↗':'TECHNOLOGIE IN BEWEGUNG ↗',
  'OPEN':'ÖFFNEN','EXPERIENCE':'ERFAHRUNG','Work':'Projekte','Experience':'Erfahrung','Skills':'Skills','Education':'Ausbildung','Contact':'Kontakt',
  'Software engineer crafting scalable systems':'Softwareentwicklerin für skalierbare Systeme','with a sharp eye for how they feel.':'mit einem scharfen Blick dafür, wie sie sich anfühlen.',
  'SELECTED EXPERIENCE':'AUSGEWÄHLTE ERFAHRUNG','09 SIGNALS':'09 SIGNALE','PUBLIC PRODUCT':'ÖFFENTLICHES PRODUKT','STUDENT TECH SYSTEMS':'STUDENTISCHE TECH-SYSTEME','TRAVEL PRODUCT LIVE':'REISEPRODUKT LIVE','DRAG / MOVE TO EXPLORE':'ZIEHEN / BEWEGEN ZUM ERKUNDEN','SCROLL VELOCITY CONTROLS THE ORBIT':'SCROLLTEMPO STEUERT DIE UMLAUFBAHN',
  'CLOUD INFRASTRUCTURE':'CLOUD-INFRASTRUKTUR','ACTIVE / SHIPPED PROJECTS':'AKTIVE / AUSGELIEFERTE PROJEKTE','STORYBOOK COMPONENTS':'STORYBOOK-KOMPONENTEN','UI DESIGNED FROM ZERO':'UI VON GRUND AUF ENTWORFEN','MARKETPLACE SHIPPED':'MARKTPLATZ VERÖFFENTLICHT','FULL WEBSITE LIVE':'VOLLSTÄNDIGE WEBSITE LIVE',
  '[ TRUSTED SIGNAL / 2023—NOW ]':'[ VERTRAUTES NETZWERK / 2023—HEUTE ]','COMPANIES & PRODUCTS I HAVE HELPED BUILD':'UNTERNEHMEN UND PRODUKTE, AN DENEN ICH MITGEWIRKT HABE',
  '[ 00 / PROFILE ]':'[ 00 / PROFIL ]','I build at the point where':'Ich arbeite dort, wo','robust engineering':'robustes Engineering',', product thinking and visual precision meet.':', Produktdenken und visuelle Präzision zusammentreffen.','BASED IN MAASTRICHT, NL':'MIT SITZ IN MAASTRICHT, NL','WORKING WORLDWIDE':'WELTWEIT TÄTIG',
  '[ SELECTED DELIVERY ]':'[ AUSGEWÄHLTE ARBEITEN ]','PUBLIC PROOF.':'ÖFFENTLICHE BELEGE.','PRIVATE DEPTH.':'PRIVATE TIEFE.','3 PUBLIC LINKS + NDA WORK ↘':'3 ÖFFENTLICHE LINKS + NDA-ARBEIT ↘','PRODUCTION WEBSITE':'LIVE-WEBSITE','TOURISM WEBSITE':'TOURISMUS-WEBSITE',
  "MOST OF THE WORK ISN’T PUBLIC.":'DIE MEISTE ARBEIT IST NICHT ÖFFENTLICH.','Much of my production experience is built for internal company platforms, private B2B products or clients protected by NDA. The links below are public examples — not the full scope of what I have designed and shipped.':'Ein großer Teil meiner Produktionserfahrung betrifft interne Unternehmensplattformen, private B2B-Produkte und Kunden unter NDA. Die Links sind öffentliche Beispiele — nicht der gesamte Umfang meiner Arbeit.',
  'INTERNAL TOOLS':'INTERNE TOOLS','B2B PLATFORMS':'B2B-PLATTFORMEN','NDA PRODUCTS':'NDA-PRODUKTE',
  '[ 01 / EXPERIENCE ]':'[ 01 / ERFAHRUNG ]','SELECTED':'AUSGEWÄHLTE','SYSTEMS':'SYSTEME','2024—NOW ↘':'2024—HEUTE ↘','01 / CURRENT':'01 / AKTUELL','02 / CURRENT':'02 / AKTUELL','03 / PLATFORM':'03 / PLATTFORM','04 / PRODUCT':'04 / PRODUKT','05 / FOUNDER MODE':'05 / GRÜNDERIN','06 / CLIENT DELIVERY':'06 / KUNDENPROJEKT','07 / STARTUP LAB':'07 / START-UP-LAB',
  'JUN 2026 — NOW':'JUN 2026 — HEUTE','FEB 2026 — NOW':'FEB 2026 — HEUTE','OCT 2025 — MAY 2026':'OKT 2025 — MAI 2026','JAN 2025 — APR 2026':'JAN 2025 — APR 2026','JUN 2025 — JAN 2026':'JUN 2025 — JAN 2026','JUL 2025 — JAN 2026':'JUL 2025 — JAN 2026','MAR 2024 — JUL 2025':'MÄR 2024 — JUL 2025',
  'FULL-STACK & CLOUD DEVELOPER':'FULL-STACK- & CLOUD-ENTWICKLERIN','WEB DEVELOPER · FRONTEND LEAD':'WEBENTWICKLERIN · FRONTEND LEAD','FULL-STACK DEVELOPER':'FULL-STACK-ENTWICKLERIN','UI/UX DESIGNER & FRONTEND DEVELOPER':'UI/UX-DESIGNERIN & FRONTEND-ENTWICKLERIN','FOUNDER & FULL-STACK DEVELOPER':'GRÜNDERIN & FULL-STACK-ENTWICKLERIN','FRONTEND WEB DEVELOPER':'FRONTEND-WEBENTWICKLERIN',
  'Engineering backend and frontend systems for AI cloud infrastructure used in real customer environments.':'Entwicklung von Backend- und Frontendsystemen für KI-Cloud-Infrastruktur in realen Kundenumgebungen.','Scalable architectures':'Skalierbare Architekturen','Distributed systems':'Verteilte Systeme','AI cloud infrastructure':'KI-Cloud-Infrastruktur',
  'Owning frontend architecture, design scope and production UI across a profitable B2B startup with 10+ active or shipped projects.':'Verantwortung für Frontend-Architektur, Design und Produktions-UI eines profitablen B2B-Start-ups mit über 10 aktiven oder ausgelieferten Projekten.','Built and documented cloud software for radio and media production; shipped roughly 60% of the React Storybook component library.':'Cloudsoftware für Radio- und Medienproduktion entwickelt und dokumentiert; rund 60 % der React-Storybook-Bibliothek ausgeliefert.','Designed 100% of the website UI from scratch and translated the product language into responsive React interfaces.':'100 % der Website-UI von Grund auf entworfen und in responsive React-Interfaces übersetzt.','Built and shipped a modern rental marketplace with clean architecture, intuitive flows and scalable infrastructure.':'Einen modernen Mietmarktplatz mit klarer Architektur, intuitiven Abläufen und skalierbarer Infrastruktur entwickelt und veröffentlicht.','Shipped the complete public website for Kicksharing Central Asia, translating client requirements into a fast, responsive production experience.':'Die vollständige öffentliche Website für Kicksharing Central Asia als schnelle, responsive Produktionserfahrung umgesetzt.','Designed and developed responsive interfaces within the ITS-TECH organization, including ITS Reg and RS: Frontend.':'Responsive Interfaces bei ITS-TECH entworfen und entwickelt, darunter ITS Reg und RS: Frontend.','Design & business collaboration':'Zusammenarbeit mit Design und Business','Figma / UI systems':'Figma / UI-Systeme',
  '[ 02 / CAPABILITIES ]':'[ 02 / KOMPETENZEN ]','ONE ENGINEER.':'EINE ENGINEERIN.','ALL LAYERS.':'ALLE EBENEN.','I move between interface details and infrastructure decisions without losing sight of the product.':'Ich wechsle zwischen Interface-Details und Infrastrukturentscheidungen, ohne das Produkt aus dem Blick zu verlieren.',
  '[ 03 / LEARNING LOG ]':'[ 03 / AUSBILDUNG ]',"Bachelor's degree · Netherlands":'Bachelor · Niederlande','International Summer Program · Computer Science':'Internationales Sommerprogramm · Informatik','Computer Science':'Informatik',
  '[ HACKATHONS & RECOGNITION ]':'[ HACKATHONS & AUSZEICHNUNGEN ]','PROOF OF PRACTICE':'PRAXIS ALS BELEG','2025 · PRIZE WINNER':'2025 · PREISTRÄGERIN','THREE SEPARATE HACKATHONS · PRIZE WINNER':'DREI EIGENSTÄNDIGE HACKATHONS · PREISTRÄGERIN','WEB DEVELOPMENT HACKATHON':'WEBDEVELOPMENT-HACKATHON','2026 · RECOGNIZED SOLUTION':'2026 · ANERKANNTE LÖSUNG','TEAM EPOCH × AIC4NL · RECOGNITION PROVIDED ACCESS TO DUTCH AI CONGRESS 2026':'TEAM EPOCH × AIC4NL · DIE ANERKENNUNG ERMÖGLICHTE DEN BESUCH DES DUTCH AI CONGRESS 2026',
  '[ 04 / START A CONVERSATION ]':'[ 04 / LASS UNS REDEN ]',"LET'S BUILD":'LASS UNS BAUEN',"WHAT'S NEXT.":'WAS ALS NÄCHSTES KOMMT.','BACK TO TOP ↑':'NACH OBEN ↑'
}

const zh = {
  'WEBSITE IN DEVELOPMENT':'网站开发中','VIEW PREVIEW ↗':'查看预览 ↗','03 / IN DEVELOPMENT':'03 / 开发中','TRAVEL PRODUCT IN BUILD':'旅游产品开发中',
  '[ TRUSTED SIGNAL / 2023—NOW ]':'[ 合作网络 / 2023—至今 ]',
  '[ TOOLCHAIN / ALWAYS EVOLVING ]':'[ 工具链 / 持续进化 ]','TECHNOLOGY IN MOTION ↗':'技术持续前进 ↗',
  'OPEN':'打开','EXPERIENCE':'经历','Work':'项目','Experience':'经历','Skills':'技能','Education':'教育','Contact':'联系',
  'Software engineer crafting scalable systems':'打造可扩展系统的软件工程师','with a sharp eye for how they feel.':'同时关注产品的真实体验。','SELECTED EXPERIENCE':'精选经历','09 SIGNALS':'09 个信号','PUBLIC PRODUCT':'公开产品','STUDENT TECH SYSTEMS':'学生技术系统','TRAVEL PRODUCT LIVE':'旅游产品已上线','DRAG / MOVE TO EXPLORE':'拖动 / 移动以探索','SCROLL VELOCITY CONTROLS THE ORBIT':'滚动速度控制轨道',
  'CLOUD INFRASTRUCTURE':'云基础设施','ACTIVE / SHIPPED PROJECTS':'进行中 / 已交付项目','STORYBOOK COMPONENTS':'STORYBOOK 组件','UI DESIGNED FROM ZERO':'从零设计 UI','MARKETPLACE SHIPPED':'平台已上线','FULL WEBSITE LIVE':'完整网站已上线',
  '[ TRUSTED SIGNAL / 2021—NOW ]':'[ 合作网络 / 2021—至今 ]','COMPANIES & PRODUCTS I HAVE HELPED BUILD':'我参与建设的公司与产品','[ 00 / PROFILE ]':'[ 00 / 简介 ]','I build at the point where':'我的工作位于','robust engineering':'可靠工程',', product thinking and visual precision meet.':'、产品思维与视觉精度的交汇处。','BASED IN MAASTRICHT, NL':'常驻荷兰马斯特里赫特','WORKING WORLDWIDE':'面向全球工作',
  '[ SELECTED DELIVERY ]':'[ 精选成果 ]','PUBLIC PROOF.':'公开案例。','PRIVATE DEPTH.':'非公开实力。','3 PUBLIC LINKS + NDA WORK ↘':'3 个公开链接 + NDA 项目 ↘','PRODUCTION WEBSITE':'线上网站','TOURISM WEBSITE':'旅游网站',"MOST OF THE WORK ISN’T PUBLIC.":'大部分工作并不公开。','Much of my production experience is built for internal company platforms, private B2B products or clients protected by NDA. The links below are public examples — not the full scope of what I have designed and shipped.':'我的许多生产经验来自企业内部平台、私有 B2B 产品以及受 NDA 保护的客户项目。以下链接只是公开案例，并非我全部设计与交付工作的范围。','INTERNAL TOOLS':'内部工具','B2B PLATFORMS':'B2B 平台','NDA PRODUCTS':'NDA 产品',
  '[ 01 / EXPERIENCE ]':'[ 01 / 经历 ]','SELECTED':'精选','SYSTEMS':'系统','2024—NOW ↘':'2024—至今 ↘','01 / CURRENT':'01 / 当前','02 / CURRENT':'02 / 当前','03 / PLATFORM':'03 / 平台','04 / PRODUCT':'04 / 产品','05 / FOUNDER MODE':'05 / 创始人','06 / CLIENT DELIVERY':'06 / 客户项目','07 / STARTUP LAB':'07 / 创业实验室',
  'JUN 2026 — NOW':'2026年6月 — 至今','FEB 2026 — NOW':'2026年2月 — 至今','OCT 2025 — MAY 2026':'2025年10月 — 2026年5月','JAN 2025 — APR 2026':'2025年1月 — 2026年4月','JUN 2025 — JAN 2026':'2025年6月 — 2026年1月','JUL 2025 — JAN 2026':'2025年7月 — 2026年1月','MAR 2024 — JUL 2025':'2024年3月 — 2025年7月',
  'FULL-STACK & CLOUD DEVELOPER':'全栈与云开发工程师','WEB DEVELOPER · FRONTEND LEAD':'Web 开发工程师 · 前端负责人','FULL-STACK DEVELOPER':'全栈开发工程师','UI/UX DESIGNER & FRONTEND DEVELOPER':'UI/UX 设计师与前端开发工程师','FOUNDER & FULL-STACK DEVELOPER':'创始人兼全栈开发工程师','FRONTEND WEB DEVELOPER':'前端 Web 开发工程师',
  'Engineering backend and frontend systems for AI cloud infrastructure used in real customer environments.':'为真实客户环境中的 AI 云基础设施开发后端与前端系统。','Scalable architectures':'可扩展架构','Distributed systems':'分布式系统','AI cloud infrastructure':'AI 云基础设施','Owning frontend architecture, design scope and production UI across a profitable B2B startup with 10+ active or shipped projects.':'负责一家盈利 B2B 初创公司的前端架构、设计与生产 UI，涵盖 10 多个进行中或已交付项目。','Built and documented cloud software for radio and media production; shipped roughly 60% of the React Storybook component library.':'开发并记录广播与媒体制作云软件，交付约 60% 的 React Storybook 组件库。','Designed 100% of the website UI from scratch and translated the product language into responsive React interfaces.':'从零设计网站全部 UI，并将产品语言转化为响应式 React 界面。','Built and shipped a modern rental marketplace with clean architecture, intuitive flows and scalable infrastructure.':'开发并上线现代租赁平台，具备清晰架构、直观流程和可扩展基础设施。','Shipped the complete public website for Kicksharing Central Asia, translating client requirements into a fast, responsive production experience.':'交付 Kicksharing Central Asia 完整官网，将客户需求转化为快速响应的线上体验。','Designed and developed responsive interfaces within the ITS-TECH organization, including ITS Reg and RS: Frontend.':'在 ITS-TECH 设计并开发响应式界面，包括 ITS Reg 与 RS: Frontend。','Design & business collaboration':'设计与业务协作','Figma / UI systems':'Figma / UI 系统',
  '[ 02 / CAPABILITIES ]':'[ 02 / 能力 ]','ONE ENGINEER.':'一名工程师。','ALL LAYERS.':'覆盖全栈。','I move between interface details and infrastructure decisions without losing sight of the product.':'我在界面细节与基础设施决策之间切换，同时始终关注产品。','[ 03 / LEARNING LOG ]':'[ 03 / 教育 ]',"Bachelor's degree · Netherlands":'学士学位 · 荷兰','International Summer Program · Computer Science':'国际暑期项目 · 计算机科学','Computer Science':'计算机科学',
  '[ HACKATHONS & RECOGNITION ]':'[ 黑客松与认可 ]','PROOF OF PRACTICE':'实践成果','2025 · PRIZE WINNER':'2025 · 获奖者','THREE SEPARATE HACKATHONS · PRIZE WINNER':'三场独立黑客松 · 获奖者','WEB DEVELOPMENT HACKATHON':'Web 开发黑客松','2026 · RECOGNIZED SOLUTION':'2026 · 获认可方案','TEAM EPOCH × AIC4NL · RECOGNITION PROVIDED ACCESS TO DUTCH AI CONGRESS 2026':'TEAM EPOCH × AIC4NL · 方案获认可，并获得参加 DUTCH AI CONGRESS 2026 的机会','[ 04 / START A CONVERSATION ]':'[ 04 / 开始交流 ]',"LET'S BUILD":'一起创造',"WHAT'S NEXT.":'下一步。','BACK TO TOP ↑':'返回顶部 ↑'
}

// Editorial localization pass. These translations favour natural portfolio language
// over literal word-for-word equivalents and cover copy added after the first pass.
Object.assign(ru, {
  'FULL-STACK / CLOUD / CREATIVE FRONTEND':'FULL-STACK / ОБЛАЧНЫЕ СИСТЕМЫ / КРЕАТИВНЫЙ FRONTEND',
  'Software engineer crafting scalable systems':'Разрабатываю масштабируемые программные системы',
  'with a sharp eye for how they feel.':'и уделяю особое внимание тому, как они воспринимаются.',
  'SELECTED EXPERIENCE':'КЛЮЧЕВОЙ ОПЫТ','09 SIGNALS':'09 ПРОЕКТОВ','DRAG / MOVE TO EXPLORE':'ПЕРЕТАСКИВАЙТЕ, ЧТОБЫ ИССЛЕДОВАТЬ','SCROLL VELOCITY CONTROLS THE ORBIT':'СКОРОСТЬ ПРОКРУТКИ УПРАВЛЯЕТ ВРАЩЕНИЕМ',
  '[ TOOLCHAIN / ALWAYS EVOLVING ]':'[ СТЕК / ПОСТОЯННО РАЗВИВАЕТСЯ ]','TECHNOLOGY IN MOTION ↗':'ТЕХНОЛОГИИ В ДВИЖЕНИИ ↗',
  '[ TRUSTED SIGNAL / 2023—NOW ]':'[ СОТРУДНИЧЕСТВО / 2023—СЕЙЧАС ]','COMPANIES & PRODUCTS I HAVE HELPED BUILD':'КОМПАНИИ И ПРОДУКТЫ, КОТОРЫЕ Я ПОМОГАЛА СОЗДАТЬ',
  'I build at the point where':'Я создаю продукты на стыке','robust engineering':'надёжной разработки',', product thinking and visual precision meet.':', продуктового мышления и визуальной точности.',
  'BASED IN MAASTRICHT, NL':'ЖИВУ В МААСТРИХТЕ, НИДЕРЛАНДЫ','WORKING WORLDWIDE':'РАБОТАЮ С КОМАНДАМИ ПО ВСЕМУ МИРУ',
  '[ SELECTED DELIVERY ]':'[ ИЗБРАННЫЕ ПРОЕКТЫ ]','PUBLIC PROOF.':'ПУБЛИЧНЫЕ КЕЙСЫ.','PRIVATE DEPTH.':'ОПЫТ ПОД NDA.','3 PUBLIC LINKS + NDA WORK ↘':'3 ПУБЛИЧНЫХ ПРОЕКТА + РАБОТА ПОД NDA ↘',
  "MOST OF THE WORK ISN’T PUBLIC.":'БОЛЬШАЯ ЧАСТЬ МОЕЙ РАБОТЫ НЕПУБЛИЧНА.',
  'Much of my production experience is built for internal company platforms, private B2B products or clients protected by NDA. The links below are public examples — not the full scope of what I have designed and shipped.':'Значительная часть моего опыта связана с внутренними корпоративными платформами, закрытыми B2B-продуктами и клиентскими проектами под NDA. Ниже представлены публичные примеры, но они отражают лишь часть созданных и запущенных мной решений.',
  'PRODUCTION WEBSITE':'РАБОТАЮЩИЙ САЙТ','TRAVEL / DIGITAL EXPERIENCE':'ТУРИЗМ / ЦИФРОВОЙ ПРОДУКТ','PLAN':'ПЛАН','GO':'В ПУТЬ','BUILD IN PROGRESS':'В РАЗРАБОТКЕ','OPEN PREVIEW ↗':'ОТКРЫТЬ ПРЕВЬЮ ↗',
  '01 / CURRENT':'01 / ТЕКУЩАЯ РОЛЬ','02 / CURRENT':'02 / ТЕКУЩАЯ РОЛЬ','05 / FOUNDER MODE':'05 / СОБСТВЕННЫЙ ПРОДУКТ','07 / STARTUP LAB':'07 / СТАРТАП-ЛАБОРАТОРИЯ',
  'FULL-STACK & CLOUD DEVELOPER':'FULL-STACK- И CLOUD-РАЗРАБОТЧИК','WEB DEVELOPER · FRONTEND LEAD':'WEB-РАЗРАБОТЧИК · FRONTEND LEAD','FULL-STACK DEVELOPER':'FULL-STACK-РАЗРАБОТЧИК','UI/UX DESIGNER & FRONTEND DEVELOPER':'UI/UX-ДИЗАЙНЕР · FRONTEND-РАЗРАБОТЧИК','FOUNDER & FULL-STACK DEVELOPER':'ОСНОВАТЕЛЬ · FULL-STACK-РАЗРАБОТЧИК','FRONTEND WEB DEVELOPER':'FRONTEND-РАЗРАБОТЧИК',
  'Engineering backend and frontend systems for AI cloud infrastructure used in real customer environments.':'Разрабатываю backend- и frontend-системы для облачной AI-инфраструктуры, которой пользуются реальные клиенты.',
  'Owning frontend architecture, design scope and production UI across a profitable B2B startup with 10+ active or shipped projects.':'Отвечаю за frontend-архитектуру, дизайн и интерфейсы прибыльного B2B-стартапа: более 10 активных и запущенных проектов.',
  'Built and documented cloud software for radio and media production; shipped roughly 60% of the React Storybook component library.':'Разрабатывала и документировала облачную платформу для радио- и медиапроизводства; реализовала около 60% библиотеки React-компонентов в Storybook.',
  'Designed 100% of the website UI from scratch and translated the product language into responsive React interfaces.':'Полностью спроектировала интерфейс сайта с нуля и реализовала продуктовую концепцию в адаптивных React-интерфейсах.',
  'Built and shipped a modern rental marketplace with clean architecture, intuitive flows and scalable infrastructure.':'Создала и запустила современный маркетплейс аренды с продуманной архитектурой, понятными сценариями и масштабируемой инфраструктурой.',
  'Shipped the complete public website for Kicksharing Central Asia, translating client requirements into a fast, responsive production experience.':'Разработала и запустила публичный сайт Kicksharing Central Asia, превратив требования клиента в быстрый и адаптивный цифровой продукт.',
  'Designed and developed responsive interfaces within the ITS-TECH organization, including ITS Reg and RS: Frontend.':'Проектировала и разрабатывала адаптивные интерфейсы в ITS-TECH, включая проекты ITS Reg и RS: Frontend.',
  'BMSTU / STUDENT STARTUP ORGANISATION':'МГТУ / СТУДЕНЧЕСКАЯ СТАРТАП-ОРГАНИЗАЦИЯ',
  'ONE ENGINEER.':'ОДИН СПЕЦИАЛИСТ.','ALL LAYERS.':'ВЕСЬ ПРОДУКТ.','I move between interface details and infrastructure decisions without losing sight of the product.':'Работаю и с деталями интерфейса, и с инфраструктурными решениями, сохраняя целостное видение продукта.',
  '[ 03 / LEARNING LOG ]':'[ 03 / ОБРАЗОВАНИЕ ]',"Bachelor's degree · Netherlands":'Бакалавриат · Нидерланды','International Summer Program · Computer Science':'Международная летняя программа · Компьютерные науки',
  'PROOF OF PRACTICE':'РЕЗУЛЬТАТЫ НА ПРАКТИКЕ','THREE SEPARATE HACKATHONS · PRIZE WINNER':'ТРИ ОТДЕЛЬНЫХ ХАКАТОНА · ПРИЗОВЫЕ МЕСТА','2026 · RECOGNIZED SOLUTION':'2026 · РЕШЕНИЕ ОТМЕЧЕНО ЖЮРИ',
  'TEAM EPOCH × AIC4NL · RECOGNITION PROVIDED ACCESS TO DUTCH AI CONGRESS 2026':'TEAM EPOCH × AIC4NL · ОТМЕЧЕННОЕ ЖЮРИ РЕШЕНИЕ ДАЛО ВОЗМОЖНОСТЬ ПОСЕТИТЬ DUTCH AI CONGRESS 2026',
  '[ 04 / START A CONVERSATION ]':'[ 04 / СВЯЗАТЬСЯ СО МНОЙ ]',"LET'S BUILD":'ДАВАЙТЕ СОЗДАДИМ',"WHAT'S NEXT.":'СЛЕДУЮЩИЙ ПРОДУКТ.'
})

Object.assign(nl, {
  'FULL-STACK / CLOUD / CREATIVE FRONTEND':'FULL-STACK / CLOUD / CREATIEVE FRONTEND',
  'Software engineer crafting scalable systems':'Software-engineer die schaalbare systemen bouwt','with a sharp eye for how they feel.':'met veel aandacht voor hoe ze aanvoelen in gebruik.',
  'SELECTED EXPERIENCE':'UITGELICHTE ERVARING','09 SIGNALS':'09 PROJECTEN','DRAG / MOVE TO EXPLORE':'SLEEP OM TE VERKENNEN','SCROLL VELOCITY CONTROLS THE ORBIT':'SCROLLSNELHEID BEPAALT DE ROTATIE',
  '[ TRUSTED SIGNAL / 2023—NOW ]':'[ SAMENWERKINGEN / 2023—NU ]','COMPANIES & PRODUCTS I HAVE HELPED BUILD':'BEDRIJVEN EN PRODUCTEN WAARAAN IK HEB MEEGEBOUWD',
  'I build at the point where':'Ik werk op het snijvlak van','robust engineering':'robuuste softwareontwikkeling',', product thinking and visual precision meet.':', productdenken en visuele precisie.',
  'BASED IN MAASTRICHT, NL':'GEVESTIGD IN MAASTRICHT, NEDERLAND','WORKING WORLDWIDE':'WERKT SAMEN MET TEAMS WERELDWIJD',
  '[ SELECTED DELIVERY ]':'[ UITGELICHT WERK ]','PUBLIC PROOF.':'PUBLIEK WERK.','PRIVATE DEPTH.':'ERVARING ONDER NDA.','3 PUBLIC LINKS + NDA WORK ↘':'3 PUBLIEKE PROJECTEN + WERK ONDER NDA ↘',
  "MOST OF THE WORK ISN’T PUBLIC.":'EEN GROOT DEEL VAN MIJN WERK IS NIET OPENBAAR.','Much of my production experience is built for internal company platforms, private B2B products or clients protected by NDA. The links below are public examples — not the full scope of what I have designed and shipped.':'Een groot deel van mijn praktijkervaring komt uit interne bedrijfsplatforms, besloten B2B-producten en klantprojecten onder NDA. De links hieronder zijn publieke voorbeelden en tonen slechts een deel van wat ik heb ontworpen en opgeleverd.',
  'PRODUCTION WEBSITE':'LIVE WEBSITE','TRAVEL / DIGITAL EXPERIENCE':'REIZEN / DIGITALE ERVARING','PLAN':'PLAN','GO':'VERTREK','BUILD IN PROGRESS':'IN ONTWIKKELING','OPEN PREVIEW ↗':'BEKIJK PREVIEW ↗',
  '01 / CURRENT':'01 / HUIDIGE ROL','02 / CURRENT':'02 / HUIDIGE ROL','05 / FOUNDER MODE':'05 / EIGEN PRODUCT','07 / STARTUP LAB':'07 / START-UPLAB','BMSTU / STUDENT STARTUP ORGANISATION':'BMSTU / STUDENTENSTART-UPORGANISATIE',
  'Engineering backend and frontend systems for AI cloud infrastructure used in real customer environments.':'Ik ontwikkel backend- en frontendsystemen voor AI-cloudinfrastructuur die in echte klantomgevingen wordt gebruikt.',
  'Owning frontend architecture, design scope and production UI across a profitable B2B startup with 10+ active or shipped projects.':'Ik ben verantwoordelijk voor de frontendarchitectuur, het ontwerp en de productie-UI van een winstgevende B2B-start-up met meer dan tien actieve of opgeleverde projecten.',
  'Built and documented cloud software for radio and media production; shipped roughly 60% of the React Storybook component library.':'Ik ontwikkelde en documenteerde cloudsoftware voor radio- en mediaproductie en leverde ongeveer 60% van de React-componentbibliotheek in Storybook op.',
  'Designed 100% of the website UI from scratch and translated the product language into responsive React interfaces.':'Ik ontwierp de volledige website-interface vanaf nul en vertaalde de productvisie naar responsieve React-interfaces.',
  'Built and shipped a modern rental marketplace with clean architecture, intuitive flows and scalable infrastructure.':'Ik bouwde en lanceerde een moderne verhuurmarktplaats met een heldere architectuur, intuïtieve gebruikersstromen en schaalbare infrastructuur.',
  'Shipped the complete public website for Kicksharing Central Asia, translating client requirements into a fast, responsive production experience.':'Ik realiseerde de volledige publieke website voor Kicksharing Central Asia en vertaalde de klantwensen naar een snelle, responsieve gebruikerservaring.',
  'Designed and developed responsive interfaces within the ITS-TECH organization, including ITS Reg and RS: Frontend.':'Binnen ITS-TECH ontwierp en ontwikkelde ik responsieve interfaces, waaronder ITS Reg en RS: Frontend.',
  'ONE ENGINEER.':'ÉÉN ENGINEER.','ALL LAYERS.':'ALLE LAGEN.','I move between interface details and infrastructure decisions without losing sight of the product.':'Ik schakel tussen interfacedetails en infrastructuurbeslissingen zonder het product als geheel uit het oog te verliezen.',
  '[ 03 / LEARNING LOG ]':'[ 03 / OPLEIDING ]',"Bachelor's degree · Netherlands":'Bacheloropleiding · Nederland','International Summer Program · Computer Science':'Internationaal zomerprogramma · Informatica',
  'PROOF OF PRACTICE':'RESULTATEN IN DE PRAKTIJK','THREE SEPARATE HACKATHONS · PRIZE WINNER':'DRIE AFZONDERLIJKE HACKATHONS · IN DE PRIJZEN','2026 · RECOGNIZED SOLUTION':'2026 · ERKENDE OPLOSSING','TEAM EPOCH × AIC4NL · RECOGNITION PROVIDED ACCESS TO DUTCH AI CONGRESS 2026':'TEAM EPOCH × AIC4NL · DE ERKENDE OPLOSSING LEVERDE EEN UITNODIGING OP VOOR HET DUTCH AI CONGRESS 2026',
  '[ 04 / START A CONVERSATION ]':'[ 04 / NEEM CONTACT OP ]',"LET'S BUILD":'LATEN WE BOUWEN AAN',"WHAT'S NEXT.":'WAT HIERNA KOMT.'
})

Object.assign(fr, {
  'FULL-STACK / CLOUD / CREATIVE FRONTEND':'FULL-STACK / CLOUD / FRONTEND CRÉATIF','Software engineer crafting scalable systems':'Ingénieure logiciel, je conçois des systèmes évolutifs','with a sharp eye for how they feel.':'avec une attention particulière portée à l’expérience utilisateur.',
  'SELECTED EXPERIENCE':'EXPÉRIENCES CLÉS','09 SIGNALS':'09 PROJETS','DRAG / MOVE TO EXPLORE':'FAITES GLISSER POUR EXPLORER','SCROLL VELOCITY CONTROLS THE ORBIT':'LA VITESSE DE DÉFILEMENT CONTRÔLE LA ROTATION',
  '[ TRUSTED SIGNAL / 2023—NOW ]':'[ COLLABORATIONS / 2023—AUJOURD’HUI ]','COMPANIES & PRODUCTS I HAVE HELPED BUILD':'ENTREPRISES ET PRODUITS QUE J’AI CONTRIBUÉ À DÉVELOPPER',
  'I build at the point where':'Je travaille à la croisée de','robust engineering':'l’ingénierie logicielle robuste',', product thinking and visual precision meet.':', de la vision produit et de la précision visuelle.',
  'BASED IN MAASTRICHT, NL':'BASÉE À MAASTRICHT, PAYS-BAS','WORKING WORLDWIDE':'COLLABORATIONS DANS LE MONDE ENTIER',
  '[ SELECTED DELIVERY ]':'[ PROJETS SÉLECTIONNÉS ]','PUBLIC PROOF.':'PROJETS PUBLICS.','PRIVATE DEPTH.':'EXPERTISE SOUS NDA.','3 PUBLIC LINKS + NDA WORK ↘':'3 PROJETS PUBLICS + MISSIONS SOUS NDA ↘',
  "MOST OF THE WORK ISN’T PUBLIC.":'UNE GRANDE PARTIE DE MON TRAVAIL N’EST PAS PUBLIQUE.','Much of my production experience is built for internal company platforms, private B2B products or clients protected by NDA. The links below are public examples — not the full scope of what I have designed and shipped.':'Une grande partie de mon expérience concerne des plateformes internes, des produits B2B privés et des projets clients soumis à des accords de confidentialité. Les liens ci-dessous ne présentent qu’une partie des produits que j’ai conçus et mis en production.',
  'PRODUCTION WEBSITE':'SITE EN PRODUCTION','TRAVEL / DIGITAL EXPERIENCE':'VOYAGE / EXPÉRIENCE NUMÉRIQUE','PLAN':'PLANIFIER','GO':'PARTIR','BUILD IN PROGRESS':'EN COURS DE DÉVELOPPEMENT','OPEN PREVIEW ↗':'VOIR L’APERÇU ↗','BMSTU / STUDENT STARTUP ORGANISATION':'BMSTU / ORGANISATION ÉTUDIANTE DE START-UP',
  'Engineering backend and frontend systems for AI cloud infrastructure used in real customer environments.':'Je développe des systèmes backend et frontend pour une infrastructure cloud dédiée à l’IA, utilisée dans des environnements clients réels.','Owning frontend architecture, design scope and production UI across a profitable B2B startup with 10+ active or shipped projects.':'Je pilote l’architecture frontend, le design et les interfaces en production d’une start-up B2B rentable, avec plus de dix projets actifs ou livrés.','Built and documented cloud software for radio and media production; shipped roughly 60% of the React Storybook component library.':'J’ai développé et documenté une plateforme cloud pour la production radio et média, et livré environ 60 % de la bibliothèque de composants React dans Storybook.','Designed 100% of the website UI from scratch and translated the product language into responsive React interfaces.':'J’ai conçu l’intégralité de l’interface du site à partir de zéro, puis traduit la vision produit en interfaces React responsives.','Built and shipped a modern rental marketplace with clean architecture, intuitive flows and scalable infrastructure.':'J’ai conçu et lancé une marketplace de location dotée d’une architecture claire, de parcours intuitifs et d’une infrastructure évolutive.','Shipped the complete public website for Kicksharing Central Asia, translating client requirements into a fast, responsive production experience.':'J’ai réalisé et mis en ligne le site public de Kicksharing Central Asia, en transformant les besoins du client en une expérience rapide et responsive.','Designed and developed responsive interfaces within the ITS-TECH organization, including ITS Reg and RS: Frontend.':'Au sein d’ITS-TECH, j’ai conçu et développé des interfaces responsives, notamment pour ITS Reg et RS: Frontend.',
  'ONE ENGINEER.':'UNE INGÉNIEURE.','ALL LAYERS.':'TOUTES LES COUCHES.','I move between interface details and infrastructure decisions without losing sight of the product.':'Je passe des détails d’interface aux choix d’infrastructure sans jamais perdre de vue le produit dans son ensemble.',
  '[ 03 / LEARNING LOG ]':'[ 03 / FORMATION ]',"Bachelor's degree · Netherlands":'Licence · Pays-Bas','International Summer Program · Computer Science':'Programme international d’été · Informatique','PROOF OF PRACTICE':'DES RÉSULTATS CONCRETS','THREE SEPARATE HACKATHONS · PRIZE WINNER':'TROIS HACKATHONS DISTINCTS · LAURÉATE','2026 · RECOGNIZED SOLUTION':'2026 · SOLUTION REMARQUÉE','TEAM EPOCH × AIC4NL · RECOGNITION PROVIDED ACCESS TO DUTCH AI CONGRESS 2026':'TEAM EPOCH × AIC4NL · LA SOLUTION REMARQUÉE A DONNÉ ACCÈS AU DUTCH AI CONGRESS 2026','[ 04 / START A CONVERSATION ]':'[ 04 / PRENONS CONTACT ]',"LET'S BUILD":'CONSTRUISONS',"WHAT'S NEXT.":'LA SUITE.'
})

Object.assign(es, {
  'FULL-STACK / CLOUD / CREATIVE FRONTEND':'FULL-STACK / CLOUD / FRONTEND CREATIVO','Software engineer crafting scalable systems':'Ingeniera de software especializada en sistemas escalables','with a sharp eye for how they feel.':'con especial atención a cómo se sienten al usarlos.','SELECTED EXPERIENCE':'EXPERIENCIA DESTACADA','09 SIGNALS':'09 PROYECTOS','DRAG / MOVE TO EXPLORE':'ARRASTRA PARA EXPLORAR','SCROLL VELOCITY CONTROLS THE ORBIT':'LA VELOCIDAD DE DESPLAZAMIENTO CONTROLA LA ROTACIÓN',
  '[ TRUSTED SIGNAL / 2023—NOW ]':'[ COLABORACIONES / 2023—ACTUALIDAD ]','COMPANIES & PRODUCTS I HAVE HELPED BUILD':'EMPRESAS Y PRODUCTOS QUE HE AYUDADO A CREAR','I build at the point where':'Trabajo en la intersección entre','robust engineering':'la ingeniería de software sólida',', product thinking and visual precision meet.':', la visión de producto y la precisión visual.','BASED IN MAASTRICHT, NL':'RESIDO EN MAASTRICHT, PAÍSES BAJOS','WORKING WORLDWIDE':'COLABORO CON EQUIPOS DE TODO EL MUNDO',
  '[ SELECTED DELIVERY ]':'[ PROYECTOS DESTACADOS ]','PUBLIC PROOF.':'PROYECTOS PÚBLICOS.','PRIVATE DEPTH.':'EXPERIENCIA BAJO NDA.','3 PUBLIC LINKS + NDA WORK ↘':'3 PROYECTOS PÚBLICOS + TRABAJO BAJO NDA ↘',"MOST OF THE WORK ISN’T PUBLIC.":'GRAN PARTE DE MI TRABAJO NO ES PÚBLICO.','Much of my production experience is built for internal company platforms, private B2B products or clients protected by NDA. The links below are public examples — not the full scope of what I have designed and shipped.':'Gran parte de mi experiencia profesional procede de plataformas internas, productos B2B privados y proyectos de clientes sujetos a acuerdos de confidencialidad. Los enlaces siguientes son ejemplos públicos y representan solo una parte de lo que he diseñado y lanzado.',
  'PRODUCTION WEBSITE':'SITIO EN PRODUCCIÓN','TRAVEL / DIGITAL EXPERIENCE':'VIAJES / EXPERIENCIA DIGITAL','PLAN':'PLANEA','GO':'VIAJA','BUILD IN PROGRESS':'EN DESARROLLO','OPEN PREVIEW ↗':'VER ADELANTO ↗','BMSTU / STUDENT STARTUP ORGANISATION':'BMSTU / ORGANIZACIÓN ESTUDIANTIL DE START-UPS',
  'Engineering backend and frontend systems for AI cloud infrastructure used in real customer environments.':'Desarrollo sistemas backend y frontend para infraestructura cloud de IA utilizada en entornos reales de clientes.','Owning frontend architecture, design scope and production UI across a profitable B2B startup with 10+ active or shipped projects.':'Dirijo la arquitectura frontend, el diseño y las interfaces en producción de una start-up B2B rentable con más de diez proyectos activos o entregados.','Built and documented cloud software for radio and media production; shipped roughly 60% of the React Storybook component library.':'Desarrollé y documenté software cloud para producción de radio y medios, y entregué cerca del 60 % de la biblioteca de componentes React en Storybook.','Designed 100% of the website UI from scratch and translated the product language into responsive React interfaces.':'Diseñé desde cero toda la interfaz del sitio y convertí la visión del producto en interfaces React adaptables.','Built and shipped a modern rental marketplace with clean architecture, intuitive flows and scalable infrastructure.':'Desarrollé y lancé un marketplace de alquiler con arquitectura clara, recorridos intuitivos e infraestructura escalable.','Shipped the complete public website for Kicksharing Central Asia, translating client requirements into a fast, responsive production experience.':'Desarrollé y publiqué el sitio completo de Kicksharing Central Asia, transformando los requisitos del cliente en una experiencia rápida y adaptable.','Designed and developed responsive interfaces within the ITS-TECH organization, including ITS Reg and RS: Frontend.':'En ITS-TECH diseñé y desarrollé interfaces adaptables, entre ellas ITS Reg y RS: Frontend.',
  'ONE ENGINEER.':'UNA INGENIERA.','ALL LAYERS.':'TODAS LAS CAPAS.','I move between interface details and infrastructure decisions without losing sight of the product.':'Paso de los detalles de interfaz a las decisiones de infraestructura sin perder de vista el producto en su conjunto.','[ 03 / LEARNING LOG ]':'[ 03 / FORMACIÓN ]',"Bachelor's degree · Netherlands":'Grado universitario · Países Bajos','International Summer Program · Computer Science':'Programa internacional de verano · Informática','PROOF OF PRACTICE':'RESULTADOS EN LA PRÁCTICA','THREE SEPARATE HACKATHONS · PRIZE WINNER':'TRES HACKATHONES INDEPENDIENTES · PREMIADA','2026 · RECOGNIZED SOLUTION':'2026 · SOLUCIÓN DESTACADA','TEAM EPOCH × AIC4NL · RECOGNITION PROVIDED ACCESS TO DUTCH AI CONGRESS 2026':'TEAM EPOCH × AIC4NL · LA SOLUCIÓN DESTACADA DIO ACCESO AL DUTCH AI CONGRESS 2026','[ 04 / START A CONVERSATION ]':'[ 04 / HABLEMOS ]',"LET'S BUILD":'CONSTRUYAMOS',"WHAT'S NEXT.":'LO PRÓXIMO.'
})

Object.assign(de, {
  'FULL-STACK / CLOUD / CREATIVE FRONTEND':'FULL-STACK / CLOUD / KREATIVES FRONTEND','Software engineer crafting scalable systems':'Softwareentwicklerin für skalierbare Systeme','with a sharp eye for how they feel.':'mit besonderem Blick auf ein stimmiges Nutzungserlebnis.','SELECTED EXPERIENCE':'AUSGEWÄHLTE PROJEKTE','09 SIGNALS':'09 PROJEKTE','DRAG / MOVE TO EXPLORE':'ZIEHEN, UM ZU ENTDECKEN','SCROLL VELOCITY CONTROLS THE ORBIT':'DIE SCROLLGESCHWINDIGKEIT STEUERT DIE ROTATION',
  '[ TRUSTED SIGNAL / 2023—NOW ]':'[ ZUSAMMENARBEITEN / 2023—HEUTE ]','COMPANIES & PRODUCTS I HAVE HELPED BUILD':'UNTERNEHMEN UND PRODUKTE, AN DENEN ICH MITGEARBEITET HABE','I build at the point where':'Ich arbeite an der Schnittstelle von','robust engineering':'robuster Softwareentwicklung',', product thinking and visual precision meet.':', Produktdenken und visueller Präzision.','BASED IN MAASTRICHT, NL':'LEBT IN MAASTRICHT, NIEDERLANDE','WORKING WORLDWIDE':'WELTWEITE ZUSAMMENARBEIT',
  '[ SELECTED DELIVERY ]':'[ AUSGEWÄHLTE PROJEKTE ]','PUBLIC PROOF.':'ÖFFENTLICHE PROJEKTE.','PRIVATE DEPTH.':'ERFAHRUNG UNTER NDA.','3 PUBLIC LINKS + NDA WORK ↘':'3 ÖFFENTLICHE PROJEKTE + ARBEIT UNTER NDA ↘',"MOST OF THE WORK ISN’T PUBLIC.":'EIN GROSSER TEIL MEINER ARBEIT IST NICHT ÖFFENTLICH.','Much of my production experience is built for internal company platforms, private B2B products or clients protected by NDA. The links below are public examples — not the full scope of what I have designed and shipped.':'Ein großer Teil meiner Berufserfahrung stammt aus internen Unternehmensplattformen, geschlossenen B2B-Produkten und Kundenprojekten unter NDA. Die folgenden Links sind öffentliche Beispiele und zeigen nur einen Teil dessen, was ich konzipiert und veröffentlicht habe.',
  'PRODUCTION WEBSITE':'LIVE-WEBSITE','TRAVEL / DIGITAL EXPERIENCE':'REISEN / DIGITALES ERLEBNIS','PLAN':'PLANEN','GO':'LOS','BUILD IN PROGRESS':'IN ENTWICKLUNG','OPEN PREVIEW ↗':'VORSCHAU ÖFFNEN ↗','BMSTU / STUDENT STARTUP ORGANISATION':'BMSTU / STUDENTISCHE START-UP-ORGANISATION',
  'Engineering backend and frontend systems for AI cloud infrastructure used in real customer environments.':'Ich entwickle Backend- und Frontendsysteme für KI-Cloud-Infrastruktur, die in realen Kundenumgebungen eingesetzt wird.','Owning frontend architecture, design scope and production UI across a profitable B2B startup with 10+ active or shipped projects.':'Ich verantworte Frontend-Architektur, Design und produktive Benutzeroberflächen eines profitablen B2B-Start-ups mit mehr als zehn aktiven oder abgeschlossenen Projekten.','Built and documented cloud software for radio and media production; shipped roughly 60% of the React Storybook component library.':'Ich entwickelte und dokumentierte Cloudsoftware für Radio- und Medienproduktion und lieferte rund 60 % der React-Komponentenbibliothek in Storybook aus.','Designed 100% of the website UI from scratch and translated the product language into responsive React interfaces.':'Ich konzipierte die gesamte Website-Oberfläche von Grund auf und überführte die Produktvision in responsive React-Interfaces.','Built and shipped a modern rental marketplace with clean architecture, intuitive flows and scalable infrastructure.':'Ich entwickelte und veröffentlichte einen modernen Mietmarktplatz mit klarer Architektur, intuitiven Abläufen und skalierbarer Infrastruktur.','Shipped the complete public website for Kicksharing Central Asia, translating client requirements into a fast, responsive production experience.':'Ich entwickelte und veröffentlichte die vollständige Website von Kicksharing Central Asia und überführte die Kundenanforderungen in ein schnelles, responsives Nutzungserlebnis.','Designed and developed responsive interfaces within the ITS-TECH organization, including ITS Reg and RS: Frontend.':'Bei ITS-TECH konzipierte und entwickelte ich responsive Interfaces, darunter ITS Reg und RS: Frontend.',
  'ONE ENGINEER.':'EINE ENGINEERIN.','ALL LAYERS.':'ALLE EBENEN.','I move between interface details and infrastructure decisions without losing sight of the product.':'Ich bewege mich zwischen Interface-Details und Infrastrukturentscheidungen, ohne das Gesamtprodukt aus dem Blick zu verlieren.','[ 03 / LEARNING LOG ]':'[ 03 / AUSBILDUNG ]',"Bachelor's degree · Netherlands":'Bachelorstudium · Niederlande','International Summer Program · Computer Science':'Internationales Sommerprogramm · Informatik','PROOF OF PRACTICE':'ERGEBNISSE AUS DER PRAXIS','THREE SEPARATE HACKATHONS · PRIZE WINNER':'DREI EIGENSTÄNDIGE HACKATHONS · PREISTRÄGERIN','2026 · RECOGNIZED SOLUTION':'2026 · AUSGEZEICHNETE LÖSUNG','TEAM EPOCH × AIC4NL · RECOGNITION PROVIDED ACCESS TO DUTCH AI CONGRESS 2026':'TEAM EPOCH × AIC4NL · DIE AUSGEZEICHNETE LÖSUNG ERMÖGLICHTE DIE TEILNAHME AM DUTCH AI CONGRESS 2026','[ 04 / START A CONVERSATION ]':'[ 04 / KONTAKT AUFNEHMEN ]',"LET'S BUILD":'LASS UNS',"WHAT'S NEXT.":'DAS NÄCHSTE BAUEN.'
})

Object.assign(zh, {
  'FULL-STACK / CLOUD / CREATIVE FRONTEND':'全栈 / 云计算 / 创意前端','Software engineer crafting scalable systems':'专注于构建可扩展系统的软件工程师','with a sharp eye for how they feel.':'也始终关注产品使用时的真实感受。','SELECTED EXPERIENCE':'精选项目经历','09 SIGNALS':'09 个项目','DRAG / MOVE TO EXPLORE':'拖动浏览','SCROLL VELOCITY CONTROLS THE ORBIT':'滚动速度控制旋转',
  '[ TRUSTED SIGNAL / 2023—NOW ]':'[ 合作经历 / 2023—至今 ]','COMPANIES & PRODUCTS I HAVE HELPED BUILD':'我参与打造的企业与产品','I build at the point where':'我的工作连接','robust engineering':'可靠的软件工程',', product thinking and visual precision meet.':'、产品思维与视觉表达。','BASED IN MAASTRICHT, NL':'现居荷兰马斯特里赫特','WORKING WORLDWIDE':'与全球团队合作',
  '[ SELECTED DELIVERY ]':'[ 精选项目 ]','PUBLIC PROOF.':'公开案例。','PRIVATE DEPTH.':'保密项目经验。','3 PUBLIC LINKS + NDA WORK ↘':'3 个公开项目 + 保密项目经验 ↘',"MOST OF THE WORK ISN’T PUBLIC.":'我的许多工作无法公开展示。','Much of my production experience is built for internal company platforms, private B2B products or clients protected by NDA. The links below are public examples — not the full scope of what I have designed and shipped.':'我的许多实战经验来自企业内部平台、非公开 B2B 产品以及受保密协议保护的客户项目。以下链接仅为公开案例，只展示了我所设计并上线项目的一部分。',
  'PRODUCTION WEBSITE':'已上线网站','TRAVEL / DIGITAL EXPERIENCE':'旅行 / 数字体验','PLAN':'计划','GO':'出发','BUILD IN PROGRESS':'开发中','OPEN PREVIEW ↗':'查看预览 ↗','BMSTU / STUDENT STARTUP ORGANISATION':'鲍曼莫斯科国立技术大学 / 学生创业组织',
  'Engineering backend and frontend systems for AI cloud infrastructure used in real customer environments.':'为真实客户环境中的 AI 云基础设施开发前端与后端系统。','Owning frontend architecture, design scope and production UI across a profitable B2B startup with 10+ active or shipped projects.':'负责一家盈利 B2B 初创公司的前端架构、设计与生产界面，覆盖十余个在研或已交付项目。','Built and documented cloud software for radio and media production; shipped roughly 60% of the React Storybook component library.':'开发并维护广播与媒体制作云平台，完成约 60% 的 React Storybook 组件库。','Designed 100% of the website UI from scratch and translated the product language into responsive React interfaces.':'从零完成网站全部界面设计，并将产品理念落地为响应式 React 界面。','Built and shipped a modern rental marketplace with clean architecture, intuitive flows and scalable infrastructure.':'开发并上线现代租赁平台，具备清晰架构、直观流程与可扩展基础设施。','Shipped the complete public website for Kicksharing Central Asia, translating client requirements into a fast, responsive production experience.':'开发并上线 Kicksharing Central Asia 官方网站，将客户需求转化为快速、流畅且适配多端的产品体验。','Designed and developed responsive interfaces within the ITS-TECH organization, including ITS Reg and RS: Frontend.':'在 ITS-TECH 负责响应式界面的设计与开发，包括 ITS Reg 和 RS: Frontend。',
  'ONE ENGINEER.':'一名工程师。','ALL LAYERS.':'贯穿全栈。','I move between interface details and infrastructure decisions without losing sight of the product.':'我能在界面细节与基础设施决策之间切换，同时始终把握产品整体。','[ 03 / LEARNING LOG ]':'[ 03 / 教育经历 ]',"Bachelor's degree · Netherlands":'本科 · 荷兰','International Summer Program · Computer Science':'国际暑期课程 · 计算机科学','PROOF OF PRACTICE':'用成果证明实践','THREE SEPARATE HACKATHONS · PRIZE WINNER':'三场独立黑客松 · 均获奖项','2026 · RECOGNIZED SOLUTION':'2026 · 方案获评审认可','TEAM EPOCH × AIC4NL · RECOGNITION PROVIDED ACCESS TO DUTCH AI CONGRESS 2026':'TEAM EPOCH × AIC4NL · 方案获得认可，并受邀参加 DUTCH AI CONGRESS 2026','[ 04 / START A CONVERSATION ]':'[ 04 / 联系我 ]',"LET'S BUILD":'一起打造',"WHAT'S NEXT.":'下一个产品。'
})

Object.assign(ru, {'with a sharp eye for how they':'и уделяю особое внимание тому, как они','feel.':'ощущаются.','Storybook systems':'Системы компонентов Storybook','Product delivery':'Запуск продукта','COMPUTER SCIENCE':'КОМПЬЮТЕРНЫЕ НАУКИ'})
Object.assign(nl, {'with a sharp eye for how they':'met veel aandacht voor hoe ze in gebruik','feel.':'aanvoelen.','Storybook systems':'Storybook-componentsystemen','Product delivery':'Productoplevering','COMPUTER SCIENCE':'INFORMATICA'})
Object.assign(fr, {'with a sharp eye for how they':'en accordant une attention particulière à leur','feel.':'expérience d’utilisation.','Storybook systems':'Systèmes de composants Storybook','Product delivery':'Mise en production','COMPUTER SCIENCE':'INFORMATIQUE'})
Object.assign(es, {'with a sharp eye for how they':'con especial atención a cómo se','feel.':'sienten al usarlos.','Storybook systems':'Sistemas de componentes Storybook','Product delivery':'Entrega de producto','COMPUTER SCIENCE':'INFORMÁTICA'})
Object.assign(de, {'with a sharp eye for how they':'mit besonderem Blick darauf, wie sie sich','feel.':'in der Nutzung anfühlen.','Storybook systems':'Storybook-Komponentensysteme','Product delivery':'Produktumsetzung','COMPUTER SCIENCE':'INFORMATIK'})
Object.assign(zh, {'with a sharp eye for how they':'同时关注产品在使用时的','feel.':'真实感受。','Storybook systems':'Storybook 组件体系','Product delivery':'产品交付','COMPUTER SCIENCE':'计算机科学'})

Object.assign(ru, {'PREVIEW AVAILABLE':'ДОСТУПНО ПРЕВЬЮ','WEBSITE PREVIEW':'ПРЕВЬЮ САЙТА','FRONTEND SYSTEMS':'FRONTEND-СИСТЕМЫ','BACKEND & APIS':'BACKEND И API','CLOUD & DEVOPS':'ОБЛАКО И DEVOPS','DATA & STORAGE':'ДАННЫЕ И ХРАНЕНИЕ','PRODUCT DESIGN':'ПРОДУКТОВЫЙ ДИЗАЙН','ENGINEERING LANGUAGES':'ЯЗЫКИ ПРОГРАММИРОВАНИЯ','QUALITY & PERFORMANCE':'КАЧЕСТВО И ПРОИЗВОДИТЕЛЬНОСТЬ','AI & COMPUTING':'AI И ВЫЧИСЛЕНИЯ','PRODUCT & COLLABORATION':'ПРОДУКТ И КОМАНДНАЯ РАБОТА','ARTIFICIAL INTELLIGENCE · MACHINE LEARNING':'ИСКУССТВЕННЫЙ ИНТЕЛЛЕКТ · МАШИННОЕ ОБУЧЕНИЕ','FULL-STACK DELIVERY · AGILE · SCRUM · TEAMWORK':'FULL-STACK-РАЗРАБОТКА · AGILE · SCRUM · КОМАНДНАЯ РАБОТА'})
Object.assign(nl, {'PREVIEW AVAILABLE':'PREVIEW BESCHIKBAAR','FRONTEND SYSTEMS':'FRONTENDSYSTEMEN','BACKEND & APIS':'BACKEND & API’S','CLOUD & DEVOPS':'CLOUD & DEVOPS','DATA & STORAGE':'DATA & OPSLAG','PRODUCT DESIGN':'PRODUCTDESIGN','ENGINEERING LANGUAGES':'PROGRAMMEERTALEN','QUALITY & PERFORMANCE':'KWALITEIT & PRESTATIES','AI & COMPUTING':'AI & COMPUTING','PRODUCT & COLLABORATION':'PRODUCT & SAMENWERKING','ARTIFICIAL INTELLIGENCE · MACHINE LEARNING':'ARTIFICIËLE INTELLIGENTIE · MACHINE LEARNING','FULL-STACK DELIVERY · AGILE · SCRUM · TEAMWORK':'FULL-STACK OPLEVERING · AGILE · SCRUM · TEAMWERK'})
Object.assign(fr, {'PREVIEW AVAILABLE':'APERÇU DISPONIBLE','FRONTEND SYSTEMS':'SYSTÈMES FRONTEND','BACKEND & APIS':'BACKEND & API','CLOUD & DEVOPS':'CLOUD & DEVOPS','DATA & STORAGE':'DONNÉES & STOCKAGE','PRODUCT DESIGN':'DESIGN PRODUIT','ENGINEERING LANGUAGES':'LANGAGES DE PROGRAMMATION','QUALITY & PERFORMANCE':'QUALITÉ & PERFORMANCE','AI & COMPUTING':'IA & INFORMATIQUE','PRODUCT & COLLABORATION':'PRODUIT & COLLABORATION','ARTIFICIAL INTELLIGENCE · MACHINE LEARNING':'INTELLIGENCE ARTIFICIELLE · APPRENTISSAGE AUTOMATIQUE','FULL-STACK DELIVERY · AGILE · SCRUM · TEAMWORK':'LIVRAISON FULL-STACK · AGILE · SCRUM · TRAVAIL D’ÉQUIPE'})
Object.assign(es, {'PREVIEW AVAILABLE':'VISTA PREVIA DISPONIBLE','FRONTEND SYSTEMS':'SISTEMAS FRONTEND','BACKEND & APIS':'BACKEND Y API','CLOUD & DEVOPS':'CLOUD Y DEVOPS','DATA & STORAGE':'DATOS Y ALMACENAMIENTO','PRODUCT DESIGN':'DISEÑO DE PRODUCTO','ENGINEERING LANGUAGES':'LENGUAJES DE PROGRAMACIÓN','QUALITY & PERFORMANCE':'CALIDAD Y RENDIMIENTO','AI & COMPUTING':'IA Y COMPUTACIÓN','PRODUCT & COLLABORATION':'PRODUCTO Y COLABORACIÓN','ARTIFICIAL INTELLIGENCE · MACHINE LEARNING':'INTELIGENCIA ARTIFICIAL · APRENDIZAJE AUTOMÁTICO','FULL-STACK DELIVERY · AGILE · SCRUM · TEAMWORK':'DESARROLLO FULL-STACK · AGILE · SCRUM · TRABAJO EN EQUIPO'})
Object.assign(de, {'PREVIEW AVAILABLE':'VORSCHAU VERFÜGBAR','FRONTEND SYSTEMS':'FRONTEND-SYSTEME','BACKEND & APIS':'BACKEND & APIS','CLOUD & DEVOPS':'CLOUD & DEVOPS','DATA & STORAGE':'DATEN & SPEICHERUNG','PRODUCT DESIGN':'PRODUKTDESIGN','ENGINEERING LANGUAGES':'PROGRAMMIERSPRACHEN','QUALITY & PERFORMANCE':'QUALITÄT & PERFORMANCE','AI & COMPUTING':'KI & COMPUTING','PRODUCT & COLLABORATION':'PRODUKT & ZUSAMMENARBEIT','ARTIFICIAL INTELLIGENCE · MACHINE LEARNING':'KÜNSTLICHE INTELLIGENZ · MASCHINELLES LERNEN','FULL-STACK DELIVERY · AGILE · SCRUM · TEAMWORK':'FULL-STACK-UMSETZUNG · AGILE · SCRUM · TEAMARBEIT'})
Object.assign(zh, {'PREVIEW AVAILABLE':'可查看预览','FRONTEND SYSTEMS':'前端系统','BACKEND & APIS':'后端与 API','CLOUD & DEVOPS':'云计算与 DEVOPS','DATA & STORAGE':'数据与存储','PRODUCT DESIGN':'产品设计','ENGINEERING LANGUAGES':'编程语言','QUALITY & PERFORMANCE':'质量与性能','AI & COMPUTING':'人工智能与计算','PRODUCT & COLLABORATION':'产品与协作','ARTIFICIAL INTELLIGENCE · MACHINE LEARNING':'人工智能 · 机器学习','FULL-STACK DELIVERY · AGILE · SCRUM · TEAMWORK':'全栈交付 · 敏捷开发 · SCRUM · 团队协作'})

Object.assign(nl, {'WEBSITE PREVIEW':'WEBSITEPREVIEW'})
Object.assign(fr, {'WEBSITE PREVIEW':'APERÇU DU SITE'})
Object.assign(es, {'WEBSITE PREVIEW':'VISTA PREVIA DEL SITIO'})
Object.assign(de, {'WEBSITE PREVIEW':'WEBSITE-VORSCHAU'})
Object.assign(zh, {'WEBSITE PREVIEW':'网站预览'})

Object.assign(ru, { 'Education':'Учёба', 'Contact':'Связь' })
Object.assign(nl, { 'Skills':'Skills', 'Education':'Studie' })
Object.assign(fr, { 'Education':'Études' })
Object.assign(es, { 'Education':'Formación' })
Object.assign(de, { 'Education':'Bildung' })
Object.assign(ru, { 'Exchange Programme · Computer Science':'Программа обмена · Компьютерные науки' })
Object.assign(nl, { 'Exchange Programme · Computer Science':'Uitwisselingsprogramma · Informatica' })
Object.assign(fr, { 'Exchange Programme · Computer Science':'Programme d’échange · Informatique' })
Object.assign(es, { 'Exchange Programme · Computer Science':'Programa de intercambio · Informática' })
Object.assign(de, { 'Exchange Programme · Computer Science':'Austauschprogramm · Informatik' })
Object.assign(zh, { 'Exchange Programme · Computer Science':'交换项目 · 计算机科学' })

const dictionaries = { ru, nl, fr, es, de, zh }

let language = 'en'
export const t = text => dictionaries[language]?.[text] || text

function translateTextNodes() {
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT)
  while (walker.nextNode()) {
    const node = walker.currentNode
    if (!node.parentElement || ['SCRIPT','STYLE'].includes(node.parentElement.tagName)) continue
    if (node.__originalText === undefined) node.__originalText = node.nodeValue
    const original = node.__originalText, trimmed = original.trim()
    if (!trimmed) continue
    const translated = dictionaries[language]?.[trimmed] || trimmed
    node.nodeValue = original.replace(trimmed, translated)
  }
}

function updateControls() {
  document.documentElement.lang = language
  const control = document.querySelector('.language')
  const labels = { en:'EN', ru:'RU', nl:'NL', fr:'FR', es:'ES', de:'DE', zh:'中文' }
  control.querySelector('[data-current-language]').textContent = labels[language]
  document.querySelectorAll('[data-lang]').forEach(option => { const active = option.dataset.lang === language; option.classList.toggle('active', active); option.setAttribute('aria-selected', String(active)) })
  const ariaLabels = { en:'Switch language', ru:'Выбрать язык', nl:'Taal kiezen', fr:'Choisir la langue', es:'Elegir idioma', de:'Sprache auswählen', zh:'选择语言' }
  control.setAttribute('aria-label', ariaLabels[language])
  document.querySelector('.language-menu')?.setAttribute('aria-label', ariaLabels[language])
  const titles = { en:'Sofya Grishkova — Software Engineer', ru:'Софья Гришкова — software engineer', nl:'Sofya Grishkova — software-engineer', fr:'Sofya Grishkova — ingénieure logiciel', es:'Sofya Grishkova — ingeniera de software', de:'Sofya Grishkova — Softwareentwicklerin', zh:'Sofya Grishkova — 软件工程师' }
  document.title = titles[language]
}

export function initI18n() {
  const stored = localStorage.getItem('grisshk-language')
  const browserLanguage = navigator.language.toLowerCase().split('-')[0]
  language = stored || (['ru','nl','fr','es','de','zh'].includes(browserLanguage) ? browserLanguage : 'en')
  const control = document.querySelector('.language')
  const picker = document.querySelector('.language-picker')
  control.addEventListener('click', () => { const open = picker.classList.toggle('open'); control.setAttribute('aria-expanded', String(open)) })
  picker.querySelectorAll('[data-lang]').forEach(option => option.addEventListener('click', () => {
    language = option.dataset.lang
    localStorage.setItem('grisshk-language', language)
    translateTextNodes(); updateControls()
    dispatchEvent(new CustomEvent('languagechange', { detail: { language } }))
    picker.classList.remove('open'); control.setAttribute('aria-expanded', 'false')
  }))
  document.addEventListener('click', event => { if (!picker.contains(event.target)) { picker.classList.remove('open'); control.setAttribute('aria-expanded', 'false') } })
  document.addEventListener('keydown', event => { if (event.key === 'Escape') { picker.classList.remove('open'); control.setAttribute('aria-expanded', 'false'); control.focus() } })
  translateTextNodes(); updateControls()
}

export const getLanguage = () => language
